/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreClient from "@azure/core-client";

export const HourlyForecastResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "HourlyForecastResponse",
    modelProperties: {
      forecasts: {
        serializedName: "forecasts",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "HourlyForecast"
            }
          }
        }
      }
    }
  }
};

export const HourlyForecast: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "HourlyForecast",
    modelProperties: {
      date: {
        serializedName: "date",
        type: {
          name: "String"
        }
      },
      iconCode: {
        serializedName: "iconCode",
        type: {
          name: "Number"
        }
      },
      iconPhrase: {
        serializedName: "iconPhrase",
        type: {
          name: "String"
        }
      },
      hasPrecipitation: {
        serializedName: "hasPrecipitation",
        type: {
          name: "Boolean"
        }
      },
      isDaylight: {
        serializedName: "isDaylight",
        type: {
          name: "Boolean"
        }
      },
      temperature: {
        serializedName: "temperature",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      realFeelTemperature: {
        serializedName: "realFeelTemperature",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      wetBulbTemperature: {
        serializedName: "wetBulbTemperature",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      dewPoint: {
        serializedName: "dewPoint",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      wind: {
        serializedName: "wind",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      windGust: {
        serializedName: "windGust",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      relativeHumidity: {
        serializedName: "relativeHumidity",
        type: {
          name: "Number"
        }
      },
      visibility: {
        serializedName: "visibility",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      ceiling: {
        serializedName: "ceiling",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      uvIndex: {
        serializedName: "uvIndex",
        type: {
          name: "Number"
        }
      },
      uvIndexPhrase: {
        serializedName: "uvIndexPhrase",
        type: {
          name: "String"
        }
      },
      precipitationProbability: {
        serializedName: "precipitationProbability",
        type: {
          name: "Number"
        }
      },
      rainProbability: {
        serializedName: "rainProbability",
        type: {
          name: "Number"
        }
      },
      snowProbability: {
        serializedName: "snowProbability",
        type: {
          name: "Number"
        }
      },
      iceProbability: {
        serializedName: "iceProbability",
        type: {
          name: "Number"
        }
      },
      totalLiquid: {
        serializedName: "totalLiquid",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      rain: {
        serializedName: "rain",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      snow: {
        serializedName: "snow",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      ice: {
        serializedName: "ice",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      cloudCover: {
        serializedName: "cloudCover",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const WeatherUnit: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WeatherUnit",
    modelProperties: {
      value: {
        serializedName: "value",
        type: {
          name: "Number"
        }
      },
      unit: {
        serializedName: "unit",
        type: {
          name: "String"
        }
      },
      unitType: {
        serializedName: "unitType",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const WindDetails: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WindDetails",
    modelProperties: {
      direction: {
        serializedName: "direction",
        type: {
          name: "Composite",
          className: "WindDirection"
        }
      },
      speed: {
        serializedName: "speed",
        type: {
          name: "Composite",
          className: "WindSpeed"
        }
      }
    }
  }
};

export const WindDirection: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WindDirection",
    modelProperties: {
      degrees: {
        serializedName: "degrees",
        type: {
          name: "Number"
        }
      },
      localizedDescription: {
        serializedName: "localizedDescription",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WindSpeed: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WindSpeed",
    modelProperties: {
      value: {
        serializedName: "value",
        type: {
          name: "Number"
        }
      },
      unit: {
        serializedName: "unit",
        type: {
          name: "String"
        }
      },
      unitType: {
        serializedName: "unitType",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ErrorResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "ErrorResponse",
    modelProperties: {
      error: {
        serializedName: "error",
        type: {
          name: "Composite",
          className: "ErrorDetail"
        }
      }
    }
  }
};

export const ErrorDetail: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "ErrorDetail",
    modelProperties: {
      code: {
        serializedName: "code",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      target: {
        serializedName: "target",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      details: {
        serializedName: "details",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ErrorDetail"
            }
          }
        }
      },
      additionalInfo: {
        serializedName: "additionalInfo",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ErrorAdditionalInfo"
            }
          }
        }
      }
    }
  }
};

export const ErrorAdditionalInfo: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "ErrorAdditionalInfo",
    modelProperties: {
      type: {
        serializedName: "type",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      info: {
        serializedName: "info",
        readOnly: true,
        type: {
          name: "Dictionary",
          value: { type: { name: "any" } }
        }
      }
    }
  }
};

export const MinuteForecastResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "MinuteForecastResponse",
    modelProperties: {
      summary: {
        serializedName: "summary",
        type: {
          name: "Composite",
          className: "MinuteForecastSummary"
        }
      },
      intervalSummaries: {
        serializedName: "intervalSummaries",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "IntervalSummary"
            }
          }
        }
      },
      intervals: {
        serializedName: "intervals",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ForecastInterval"
            }
          }
        }
      }
    }
  }
};

export const MinuteForecastSummary: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "MinuteForecastSummary",
    modelProperties: {
      briefPhrase60: {
        serializedName: "briefPhrase60",
        type: {
          name: "String"
        }
      },
      shortPhrase: {
        serializedName: "shortPhrase",
        type: {
          name: "String"
        }
      },
      briefPhrase: {
        serializedName: "briefPhrase",
        type: {
          name: "String"
        }
      },
      longPhrase: {
        serializedName: "longPhrase",
        type: {
          name: "String"
        }
      },
      iconCode: {
        serializedName: "iconCode",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const IntervalSummary: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "IntervalSummary",
    modelProperties: {
      startMinute: {
        serializedName: "startMinute",
        type: {
          name: "Number"
        }
      },
      endMinute: {
        serializedName: "endMinute",
        type: {
          name: "Number"
        }
      },
      totalMinutes: {
        serializedName: "totalMinutes",
        type: {
          name: "Number"
        }
      },
      shortPhrase: {
        serializedName: "shortPhrase",
        type: {
          name: "String"
        }
      },
      briefPhrase: {
        serializedName: "briefPhrase",
        type: {
          name: "String"
        }
      },
      longPhrase: {
        serializedName: "longPhrase",
        type: {
          name: "String"
        }
      },
      iconCode: {
        serializedName: "iconCode",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ForecastInterval: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "ForecastInterval",
    modelProperties: {
      startTime: {
        serializedName: "startTime",
        type: {
          name: "String"
        }
      },
      minute: {
        serializedName: "minute",
        type: {
          name: "Number"
        }
      },
      dbz: {
        serializedName: "dbz",
        type: {
          name: "Number"
        }
      },
      shortPhrase: {
        serializedName: "shortPhrase",
        type: {
          name: "String"
        }
      },
      threshold: {
        serializedName: "threshold",
        type: {
          name: "String"
        }
      },
      color: {
        serializedName: "color",
        type: {
          name: "Composite",
          className: "ColorValue"
        }
      },
      simplifiedColor: {
        serializedName: "simplifiedColor",
        type: {
          name: "Composite",
          className: "ColorValue"
        }
      },
      precipitationType: {
        serializedName: "precipitationType",
        type: {
          name: "String"
        }
      },
      iconCode: {
        serializedName: "iconCode",
        type: {
          name: "Number"
        }
      },
      cloudCover: {
        serializedName: "cloudCover",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const ColorValue: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "ColorValue",
    modelProperties: {
      red: {
        serializedName: "red",
        type: {
          name: "Number"
        }
      },
      green: {
        serializedName: "green",
        type: {
          name: "Number"
        }
      },
      blue: {
        serializedName: "blue",
        type: {
          name: "Number"
        }
      },
      hex: {
        serializedName: "hex",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const QuarterDayForecastResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "QuarterDayForecastResponse",
    modelProperties: {
      forecasts: {
        serializedName: "forecasts",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "QuarterDayForecast"
            }
          }
        }
      }
    }
  }
};

export const QuarterDayForecast: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "QuarterDayForecast",
    modelProperties: {
      date: {
        serializedName: "date",
        type: {
          name: "String"
        }
      },
      effectiveDate: {
        serializedName: "effectiveDate",
        type: {
          name: "String"
        }
      },
      quarter: {
        serializedName: "quarter",
        type: {
          name: "Number"
        }
      },
      iconCode: {
        serializedName: "iconCode",
        type: {
          name: "Number"
        }
      },
      iconPhrase: {
        serializedName: "iconPhrase",
        type: {
          name: "String"
        }
      },
      phrase: {
        serializedName: "phrase",
        type: {
          name: "String"
        }
      },
      temperature: {
        serializedName: "temperature",
        type: {
          name: "Composite",
          className: "WeatherUnitRange"
        }
      },
      realFeelTemperature: {
        serializedName: "realFeelTemperature",
        type: {
          name: "Composite",
          className: "WeatherUnitRange"
        }
      },
      dewPoint: {
        serializedName: "dewPoint",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      relativeHumidity: {
        serializedName: "relativeHumidity",
        type: {
          name: "Number"
        }
      },
      wind: {
        serializedName: "wind",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      windGust: {
        serializedName: "windGust",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      visibility: {
        serializedName: "visibility",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      cloudCover: {
        serializedName: "cloudCover",
        type: {
          name: "Number"
        }
      },
      hasPrecipitation: {
        serializedName: "hasPrecipitation",
        type: {
          name: "Boolean"
        }
      },
      precipitationType: {
        serializedName: "precipitationType",
        type: {
          name: "String"
        }
      },
      precipitationIntensity: {
        serializedName: "precipitationIntensity",
        type: {
          name: "String"
        }
      },
      precipitationProbability: {
        serializedName: "precipitationProbability",
        type: {
          name: "Number"
        }
      },
      thunderstormProbability: {
        serializedName: "thunderstormProbability",
        type: {
          name: "Number"
        }
      },
      totalLiquid: {
        serializedName: "totalLiquid",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      rain: {
        serializedName: "rain",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      snow: {
        serializedName: "snow",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      ice: {
        serializedName: "ice",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      }
    }
  }
};

export const WeatherUnitRange: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WeatherUnitRange",
    modelProperties: {
      minimum: {
        serializedName: "minimum",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      maximum: {
        serializedName: "maximum",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      }
    }
  }
};

export const CurrentConditionsResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "CurrentConditionsResponse",
    modelProperties: {
      results: {
        serializedName: "results",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "CurrentConditions"
            }
          }
        }
      }
    }
  }
};

export const CurrentConditions: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "CurrentConditions",
    modelProperties: {
      dateTime: {
        serializedName: "dateTime",
        type: {
          name: "String"
        }
      },
      phrase: {
        serializedName: "phrase",
        type: {
          name: "String"
        }
      },
      iconCode: {
        serializedName: "iconCode",
        type: {
          name: "Number"
        }
      },
      hasPrecipitation: {
        serializedName: "hasPrecipitation",
        type: {
          name: "Boolean"
        }
      },
      isDayTime: {
        serializedName: "isDayTime",
        type: {
          name: "Boolean"
        }
      },
      temperature: {
        serializedName: "temperature",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      realFeelTemperature: {
        serializedName: "realFeelTemperature",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      realFeelTemperatureShade: {
        serializedName: "realFeelTemperatureShade",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      relativeHumidity: {
        serializedName: "relativeHumidity",
        type: {
          name: "Number"
        }
      },
      dewPoint: {
        serializedName: "dewPoint",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      wind: {
        serializedName: "wind",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      windGust: {
        serializedName: "windGust",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      uvIndex: {
        serializedName: "uvIndex",
        type: {
          name: "Number"
        }
      },
      uvIndexPhrase: {
        serializedName: "uvIndexPhrase",
        type: {
          name: "String"
        }
      },
      visibility: {
        serializedName: "visibility",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      obstructionsToVisibility: {
        serializedName: "obstructionsToVisibility",
        type: {
          name: "String"
        }
      },
      cloudCover: {
        serializedName: "cloudCover",
        type: {
          name: "Number"
        }
      },
      ceiling: {
        serializedName: "ceiling",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      pressure: {
        serializedName: "pressure",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      pressureTendency: {
        serializedName: "pressureTendency",
        type: {
          name: "Composite",
          className: "PressureTendency"
        }
      },
      past24HourTemperatureDeparture: {
        serializedName: "past24HourTemperatureDeparture",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      apparentTemperature: {
        serializedName: "apparentTemperature",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      windChillTemperature: {
        serializedName: "windChillTemperature",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      wetBulbTemperature: {
        serializedName: "wetBulbTemperature",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      precipitationSummary: {
        serializedName: "precipitationSummary",
        type: {
          name: "Composite",
          className: "PrecipitationSummary"
        }
      },
      temperatureSummary: {
        serializedName: "temperatureSummary",
        type: {
          name: "Composite",
          className: "TemperatureSummary"
        }
      }
    }
  }
};

export const PressureTendency: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "PressureTendency",
    modelProperties: {
      localizedDescription: {
        serializedName: "localizedDescription",
        type: {
          name: "String"
        }
      },
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const PrecipitationSummary: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "PrecipitationSummary",
    modelProperties: {
      pastHour: {
        serializedName: "pastHour",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      past3Hours: {
        serializedName: "past3Hours",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      past6Hours: {
        serializedName: "past6Hours",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      past9Hours: {
        serializedName: "past9Hours",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      past12Hours: {
        serializedName: "past12Hours",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      past18Hours: {
        serializedName: "past18Hours",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      past24Hours: {
        serializedName: "past24Hours",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      }
    }
  }
};

export const TemperatureSummary: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "TemperatureSummary",
    modelProperties: {
      past6Hours: {
        serializedName: "past6Hours",
        type: {
          name: "Composite",
          className: "TemperatureSummaryPast6Hours"
        }
      },
      past12Hours: {
        serializedName: "past12Hours",
        type: {
          name: "Composite",
          className: "TemperatureSummaryPast12Hours"
        }
      },
      past24Hours: {
        serializedName: "past24Hours",
        type: {
          name: "Composite",
          className: "TemperatureSummaryPast24Hours"
        }
      }
    }
  }
};

export const TemperatureSummaryPast6Hours: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "TemperatureSummaryPast6Hours",
    modelProperties: {
      minimum: {
        serializedName: "minimum",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      maximum: {
        serializedName: "maximum",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      }
    }
  }
};

export const TemperatureSummaryPast12Hours: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "TemperatureSummaryPast12Hours",
    modelProperties: {
      minimum: {
        serializedName: "minimum",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      maximum: {
        serializedName: "maximum",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      }
    }
  }
};

export const TemperatureSummaryPast24Hours: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "TemperatureSummaryPast24Hours",
    modelProperties: {
      minimum: {
        serializedName: "minimum",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      maximum: {
        serializedName: "maximum",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      }
    }
  }
};

export const DailyForecastResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "DailyForecastResponse",
    modelProperties: {
      summary: {
        serializedName: "summary",
        type: {
          name: "Composite",
          className: "DailyForecastSummary"
        }
      },
      forecasts: {
        serializedName: "forecasts",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "DailyForecast"
            }
          }
        }
      }
    }
  }
};

export const DailyForecastSummary: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "DailyForecastSummary",
    modelProperties: {
      startDate: {
        serializedName: "startDate",
        type: {
          name: "String"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "String"
        }
      },
      severity: {
        serializedName: "severity",
        type: {
          name: "Number"
        }
      },
      phrase: {
        serializedName: "phrase",
        type: {
          name: "String"
        }
      },
      category: {
        serializedName: "category",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const DailyForecast: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "DailyForecast",
    modelProperties: {
      date: {
        serializedName: "date",
        type: {
          name: "String"
        }
      },
      temperature: {
        serializedName: "temperature",
        type: {
          name: "Composite",
          className: "WeatherUnitRange"
        }
      },
      realFeelTemperature: {
        serializedName: "realFeelTemperature",
        type: {
          name: "Composite",
          className: "WeatherUnitRange"
        }
      },
      realFeelTemperatureShade: {
        serializedName: "realFeelTemperatureShade",
        type: {
          name: "Composite",
          className: "WeatherUnitRange"
        }
      },
      hoursOfSun: {
        serializedName: "hoursOfSun",
        type: {
          name: "Number"
        }
      },
      degreeDaySummary: {
        serializedName: "degreeDaySummary",
        type: {
          name: "Composite",
          className: "DegreeDaySummary"
        }
      },
      airAndPollen: {
        serializedName: "airAndPollen",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AirAndPollen"
            }
          }
        }
      },
      day: {
        serializedName: "day",
        type: {
          name: "Composite",
          className: "DayOrNight"
        }
      },
      night: {
        serializedName: "night",
        type: {
          name: "Composite",
          className: "DayOrNight"
        }
      },
      sources: {
        serializedName: "sources",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const DegreeDaySummary: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "DegreeDaySummary",
    modelProperties: {
      heating: {
        serializedName: "heating",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      cooling: {
        serializedName: "cooling",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      }
    }
  }
};

export const AirAndPollen: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "AirAndPollen",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "Number"
        }
      },
      category: {
        serializedName: "category",
        type: {
          name: "String"
        }
      },
      categoryValue: {
        serializedName: "categoryValue",
        type: {
          name: "Number"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const DayOrNight: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "DayOrNight",
    modelProperties: {
      iconCode: {
        serializedName: "iconCode",
        type: {
          name: "Number"
        }
      },
      iconPhrase: {
        serializedName: "iconPhrase",
        type: {
          name: "String"
        }
      },
      localSource: {
        serializedName: "localSource",
        type: {
          name: "Composite",
          className: "LocalSource"
        }
      },
      hasPrecipitation: {
        serializedName: "hasPrecipitation",
        type: {
          name: "Boolean"
        }
      },
      precipitationType: {
        serializedName: "precipitationType",
        type: {
          name: "String"
        }
      },
      precipitationIntensity: {
        serializedName: "precipitationIntensity",
        type: {
          name: "String"
        }
      },
      shortPhrase: {
        serializedName: "shortPhrase",
        type: {
          name: "String"
        }
      },
      longPhrase: {
        serializedName: "longPhrase",
        type: {
          name: "String"
        }
      },
      precipitationProbability: {
        serializedName: "precipitationProbability",
        type: {
          name: "Number"
        }
      },
      thunderstormProbability: {
        serializedName: "thunderstormProbability",
        type: {
          name: "Number"
        }
      },
      rainProbability: {
        serializedName: "rainProbability",
        type: {
          name: "Number"
        }
      },
      snowProbability: {
        serializedName: "snowProbability",
        type: {
          name: "Number"
        }
      },
      iceProbability: {
        serializedName: "iceProbability",
        type: {
          name: "Number"
        }
      },
      wind: {
        serializedName: "wind",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      windGust: {
        serializedName: "windGust",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      totalLiquid: {
        serializedName: "totalLiquid",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      rain: {
        serializedName: "rain",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      snow: {
        serializedName: "snow",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      ice: {
        serializedName: "ice",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      hoursOfPrecipitation: {
        serializedName: "hoursOfPrecipitation",
        type: {
          name: "Number"
        }
      },
      hoursOfRain: {
        serializedName: "hoursOfRain",
        type: {
          name: "Number"
        }
      },
      hoursOfSnow: {
        serializedName: "hoursOfSnow",
        type: {
          name: "Number"
        }
      },
      hoursOfIce: {
        serializedName: "hoursOfIce",
        type: {
          name: "Number"
        }
      },
      cloudCover: {
        serializedName: "cloudCover",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const LocalSource: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "LocalSource",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      weatherCode: {
        serializedName: "weatherCode",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WeatherAlongRouteResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WeatherAlongRouteResponse",
    modelProperties: {
      summary: {
        serializedName: "summary",
        type: {
          name: "Composite",
          className: "WeatherAlongRouteSummary"
        }
      },
      waypoints: {
        serializedName: "waypoints",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "WeatherWaypoint"
            }
          }
        }
      }
    }
  }
};

export const WeatherAlongRouteSummary: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WeatherAlongRouteSummary",
    modelProperties: {
      iconCode: {
        serializedName: "iconCode",
        type: {
          name: "Number"
        }
      },
      hazards: {
        serializedName: "hazards",
        type: {
          name: "Composite",
          className: "WeatherHazards"
        }
      }
    }
  }
};

export const WeatherHazards: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WeatherHazards",
    modelProperties: {
      maxHazardIndex: {
        serializedName: "maxHazardIndex",
        type: {
          name: "Number"
        }
      },
      hazardDetails: {
        serializedName: "hazardDetails",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "HazardDetail"
            }
          }
        }
      }
    }
  }
};

export const HazardDetail: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "HazardDetail",
    modelProperties: {
      hazardIndex: {
        serializedName: "hazardIndex",
        type: {
          name: "Number"
        }
      },
      hazardCode: {
        serializedName: "hazardCode",
        type: {
          name: "String"
        }
      },
      shortPhrase: {
        serializedName: "shortPhrase",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WeatherWaypoint: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WeatherWaypoint",
    modelProperties: {
      iconCode: {
        serializedName: "iconCode",
        type: {
          name: "Number"
        }
      },
      shortPhrase: {
        serializedName: "shortPhrase",
        type: {
          name: "String"
        }
      },
      isDayTime: {
        serializedName: "isDayTime",
        type: {
          name: "Boolean"
        }
      },
      cloudCover: {
        serializedName: "cloudCover",
        type: {
          name: "Number"
        }
      },
      temperature: {
        serializedName: "temperature",
        type: {
          name: "Composite",
          className: "WeatherUnit"
        }
      },
      wind: {
        serializedName: "wind",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      windGust: {
        serializedName: "windGust",
        type: {
          name: "Composite",
          className: "WindDetails"
        }
      },
      precipitation: {
        serializedName: "precipitation",
        type: {
          name: "Composite",
          className: "WeatherAlongRoutePrecipitation"
        }
      },
      lightningCount: {
        serializedName: "lightningCount",
        type: {
          name: "Number"
        }
      },
      sunGlare: {
        serializedName: "sunGlare",
        type: {
          name: "Composite",
          className: "SunGlare"
        }
      },
      hazards: {
        serializedName: "hazards",
        type: {
          name: "Composite",
          className: "WeatherHazards"
        }
      },
      notifications: {
        serializedName: "notifications",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "WeatherNotification"
            }
          }
        }
      }
    }
  }
};

export const WeatherAlongRoutePrecipitation: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WeatherAlongRoutePrecipitation",
    modelProperties: {
      dbz: {
        serializedName: "dbz",
        type: {
          name: "Number"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SunGlare: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SunGlare",
    modelProperties: {
      calculatedVehicleHeading: {
        serializedName: "calculatedVehicleHeading",
        type: {
          name: "Number"
        }
      },
      glareIndex: {
        serializedName: "glareIndex",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const WeatherNotification: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "WeatherNotification",
    modelProperties: {
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      hazardIndex: {
        serializedName: "hazardIndex",
        type: {
          name: "Number"
        }
      },
      hazardCode: {
        serializedName: "hazardCode",
        type: {
          name: "String"
        }
      },
      shortPhrase: {
        serializedName: "shortPhrase",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SevereWeatherAlertsResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SevereWeatherAlertsResponse",
    modelProperties: {
      results: {
        serializedName: "results",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SevereWeatherAlert"
            }
          }
        }
      }
    }
  }
};

export const SevereWeatherAlert: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SevereWeatherAlert",
    modelProperties: {
      countryCode: {
        serializedName: "countryCode",
        type: {
          name: "String"
        }
      },
      alertId: {
        serializedName: "alertId",
        type: {
          name: "Number"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "Composite",
          className: "SevereWeatherAlertDescription"
        }
      },
      category: {
        serializedName: "category",
        type: {
          name: "String"
        }
      },
      priority: {
        serializedName: "priority",
        type: {
          name: "Number"
        }
      },
      class: {
        serializedName: "class",
        type: {
          name: "String"
        }
      },
      level: {
        serializedName: "level",
        type: {
          name: "String"
        }
      },
      source: {
        serializedName: "source",
        type: {
          name: "String"
        }
      },
      sourceId: {
        serializedName: "sourceId",
        type: {
          name: "Number"
        }
      },
      disclaimer: {
        serializedName: "disclaimer",
        type: {
          name: "String"
        }
      },
      alertAreas: {
        serializedName: "alertAreas",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "AlertArea"
            }
          }
        }
      }
    }
  }
};

export const SevereWeatherAlertDescription: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SevereWeatherAlertDescription",
    modelProperties: {
      localized: {
        serializedName: "localized",
        type: {
          name: "String"
        }
      },
      english: {
        serializedName: "english",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const AlertArea: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "AlertArea",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      summary: {
        serializedName: "summary",
        type: {
          name: "String"
        }
      },
      startTime: {
        serializedName: "startTime",
        type: {
          name: "String"
        }
      },
      endTime: {
        serializedName: "endTime",
        type: {
          name: "String"
        }
      },
      latestStatus: {
        serializedName: "latestStatus",
        type: {
          name: "Composite",
          className: "LatestStatus"
        }
      },
      alertDetails: {
        serializedName: "alertDetails",
        type: {
          name: "String"
        }
      },
      alertDetailsLanguageCode: {
        serializedName: "alertDetailsLanguageCode",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const LatestStatus: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "LatestStatus",
    modelProperties: {
      localized: {
        serializedName: "localized",
        type: {
          name: "String"
        }
      },
      english: {
        serializedName: "english",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const DailyIndicesResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "DailyIndicesResponse",
    modelProperties: {
      results: {
        serializedName: "results",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "DailyIndex"
            }
          }
        }
      }
    }
  }
};

export const DailyIndex: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "DailyIndex",
    modelProperties: {
      indexName: {
        serializedName: "indexName",
        type: {
          name: "String"
        }
      },
      indexId: {
        serializedName: "indexId",
        type: {
          name: "Number"
        }
      },
      dateTime: {
        serializedName: "dateTime",
        type: {
          name: "String"
        }
      },
      value: {
        serializedName: "value",
        type: {
          name: "Number"
        }
      },
      category: {
        serializedName: "category",
        type: {
          name: "String"
        }
      },
      categoryValue: {
        serializedName: "categoryValue",
        type: {
          name: "Number"
        }
      },
      ascending: {
        serializedName: "ascending",
        type: {
          name: "Boolean"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      }
    }
  }
};
