/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  OperationParameter,
  OperationURLParameter,
  OperationQueryParameter
} from "@azure/core-client";

export const accept: OperationParameter = {
  parameterPath: "accept",
  mapper: {
    defaultValue: "application/json",
    isConstant: true,
    serializedName: "Accept",
    type: {
      name: "String"
    }
  }
};

export const geography: OperationURLParameter = {
  parameterPath: "geography",
  mapper: {
    serializedName: "geography",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const xMsClientId: OperationParameter = {
  parameterPath: "xMsClientId",
  mapper: {
    serializedName: "x-ms-client-id",
    type: {
      name: "String"
    }
  }
};

export const apiVersion: OperationQueryParameter = {
  parameterPath: "apiVersion",
  mapper: {
    defaultValue: "1.0",
    isConstant: true,
    serializedName: "api-version",
    type: {
      name: "String"
    }
  }
};

export const format: OperationURLParameter = {
  parameterPath: "format",
  mapper: {
    serializedName: "format",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const query: OperationQueryParameter = {
  parameterPath: "query",
  mapper: {
    serializedName: "query",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const unit: OperationQueryParameter = {
  parameterPath: ["options", "unit"],
  mapper: {
    serializedName: "unit",
    type: {
      name: "String"
    }
  }
};

export const duration: OperationQueryParameter = {
  parameterPath: ["options", "duration"],
  mapper: {
    serializedName: "duration",
    type: {
      name: "Number"
    }
  }
};

export const language: OperationQueryParameter = {
  parameterPath: ["options", "language"],
  mapper: {
    serializedName: "language",
    type: {
      name: "String"
    }
  }
};

export const interval: OperationQueryParameter = {
  parameterPath: ["options", "interval"],
  mapper: {
    serializedName: "interval",
    type: {
      name: "Number"
    }
  }
};

export const details: OperationQueryParameter = {
  parameterPath: ["options", "details"],
  mapper: {
    serializedName: "details",
    type: {
      name: "String"
    }
  }
};

export const indexId: OperationQueryParameter = {
  parameterPath: ["options", "indexId"],
  mapper: {
    serializedName: "indexId",
    type: {
      name: "Number"
    }
  }
};

export const indexGroupId: OperationQueryParameter = {
  parameterPath: ["options", "indexGroupId"],
  mapper: {
    serializedName: "indexGroupId",
    type: {
      name: "Number"
    }
  }
};
