/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreAuth from "@azure/core-auth";
import { GeolocationImpl } from "./operations";
import { Geolocation } from "./operationsInterfaces";
import { GeolocationClientContext } from "./geolocationClientContext";
import { GeolocationClientOptionalParams } from "./models";

export class GeolocationClient extends GeolocationClientContext {
  /**
   * Initializes a new instance of the GeolocationClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param options The parameter options
   */
  constructor(
    credentials: coreAuth.TokenCredential,
    options?: GeolocationClientOptionalParams
  ) {
    super(credentials, options);
    this.geolocation = new GeolocationImpl(this);
  }

  geolocation: Geolocation;
}
