/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreAuth from "@azure/core-auth";
import { WeatherImpl } from "./operations";
import { Weather } from "./operationsInterfaces";
import { WeatherClientContext } from "./weatherClientContext";
import { WeatherClientOptionalParams } from "./models";

export class WeatherClient extends WeatherClientContext {
  /**
   * Initializes a new instance of the WeatherClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param options The parameter options
   */
  constructor(
    credentials: coreAuth.TokenCredential,
    options?: WeatherClientOptionalParams
  ) {
    super(credentials, options);
    this.weather = new WeatherImpl(this);
  }

  weather: Weather;
}
