/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreAuth from "@azure/core-auth";
import { ElevationImpl } from "./operations";
import { Elevation } from "./operationsInterfaces";
import { ElevationClientContext } from "./elevationClientContext";
import { ElevationClientOptionalParams } from "./models";

export class ElevationClient extends ElevationClientContext {
  /**
   * Initializes a new instance of the ElevationClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param options The parameter options
   */
  constructor(
    credentials: coreAuth.TokenCredential,
    options?: ElevationClientOptionalParams
  ) {
    super(credentials, options);
    this.elevation = new ElevationImpl(this);
  }

  elevation: Elevation;
}
