/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreAuth from "@azure/core-auth";
import { RenderImpl, RenderV2Impl } from "./operations";
import { Render, RenderV2 } from "./operationsInterfaces";
import { RenderClientContext } from "./renderClientContext";
import { RenderClientOptionalParams } from "./models";

export class RenderClient extends RenderClientContext {
  /**
   * Initializes a new instance of the RenderClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param options The parameter options
   */
  constructor(
    credentials: coreAuth.TokenCredential,
    options?: RenderClientOptionalParams
  ) {
    super(credentials, options);
    this.render = new RenderImpl(this);
    this.renderV2 = new RenderV2Impl(this);
  }

  render: Render;
  renderV2: RenderV2;
}
