/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreClient from "@azure/core-client";

export const SearchPolygonResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchPolygonResponse",
    modelProperties: {
      additionalData: {
        serializedName: "additionalData",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchPolygonResult"
            }
          }
        }
      }
    }
  }
};

export const SearchPolygonResult: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchPolygonResult",
    modelProperties: {
      providerID: {
        serializedName: "providerID",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      error: {
        serializedName: "error",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      geometryData: {
        serializedName: "geometryData",
        type: {
          name: "Composite",
          className: "GeoJsonObject"
        }
      }
    }
  }
};

export const GeoJsonObject: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonObject",
    uberParent: "GeoJsonObject",
    polymorphicDiscriminator: {
      serializedName: "type",
      clientName: "type"
    },
    modelProperties: {
      type: {
        serializedName: "type",
        required: true,
        type: {
          name: "String"
        }
      }
    }
  }
};

export const ErrorResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "ErrorResponse",
    modelProperties: {
      error: {
        serializedName: "error",
        type: {
          name: "Composite",
          className: "ErrorDetail"
        }
      }
    }
  }
};

export const ErrorDetail: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "ErrorDetail",
    modelProperties: {
      code: {
        serializedName: "code",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      target: {
        serializedName: "target",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      details: {
        serializedName: "details",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ErrorDetail"
            }
          }
        }
      },
      additionalInfo: {
        serializedName: "additionalInfo",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ErrorAdditionalInfo"
            }
          }
        }
      }
    }
  }
};

export const ErrorAdditionalInfo: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "ErrorAdditionalInfo",
    modelProperties: {
      type: {
        serializedName: "type",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      info: {
        serializedName: "info",
        readOnly: true,
        type: {
          name: "Dictionary",
          value: { type: { name: "any" } }
        }
      }
    }
  }
};

export const SearchCommonResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchCommonResponse",
    modelProperties: {
      summary: {
        serializedName: "summary",
        type: {
          name: "Composite",
          className: "SearchCommonSummary"
        }
      },
      results: {
        serializedName: "results",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchCommonResult"
            }
          }
        }
      }
    }
  }
};

export const SearchCommonSummary: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchCommonSummary",
    modelProperties: {
      query: {
        serializedName: "query",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      queryType: {
        serializedName: "queryType",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      queryTime: {
        serializedName: "queryTime",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      numResults: {
        serializedName: "numResults",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      limit: {
        serializedName: "limit",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      offset: {
        serializedName: "offset",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      totalResults: {
        serializedName: "totalResults",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      fuzzyLevel: {
        serializedName: "fuzzyLevel",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      geoBias: {
        serializedName: "geoBias",
        type: {
          name: "Composite",
          className: "SearchCommonSummaryGeoBias"
        }
      }
    }
  }
};

export const CoordinatesPairAbbreviated: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "CoordinatesPairAbbreviated",
    modelProperties: {
      lat: {
        serializedName: "lat",
        type: {
          name: "Number"
        }
      },
      lon: {
        serializedName: "lon",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const SearchCommonResult: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchCommonResult",
    modelProperties: {
      type: {
        serializedName: "type",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      id: {
        serializedName: "id",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      score: {
        serializedName: "score",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      dist: {
        serializedName: "dist",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      info: {
        serializedName: "info",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      entityType: {
        serializedName: "entityType",
        type: {
          name: "String"
        }
      },
      poi: {
        serializedName: "poi",
        type: {
          name: "Composite",
          className: "SearchResultPoi"
        }
      },
      address: {
        serializedName: "address",
        type: {
          name: "Composite",
          className: "SearchResultAddress"
        }
      },
      position: {
        serializedName: "position",
        type: {
          name: "Composite",
          className: "CoordinatesPairAbbreviated"
        }
      },
      viewport: {
        serializedName: "viewport",
        type: {
          name: "Composite",
          className: "SearchResultViewport"
        }
      },
      entryPoints: {
        serializedName: "entryPoints",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchResultEntryPoint"
            }
          }
        }
      },
      addressRanges: {
        serializedName: "addressRanges",
        type: {
          name: "Composite",
          className: "SearchResultAddressRanges"
        }
      },
      dataSources: {
        serializedName: "dataSources",
        type: {
          name: "Composite",
          className: "DataSources"
        }
      },
      matchType: {
        serializedName: "matchType",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      detourTime: {
        serializedName: "detourTime",
        readOnly: true,
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const SearchResultPoi: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultPoi",
    modelProperties: {
      name: {
        serializedName: "name",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      phone: {
        serializedName: "phone",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      url: {
        serializedName: "url",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      categorySet: {
        serializedName: "categorySet",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchResultPoiCategorySet"
            }
          }
        }
      },
      categories: {
        serializedName: "categories",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      },
      classifications: {
        serializedName: "classifications",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchResultPoiClassification"
            }
          }
        }
      },
      brands: {
        serializedName: "brands",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchResultPoiBrand"
            }
          }
        }
      },
      openingHours: {
        serializedName: "openingHours",
        type: {
          name: "Composite",
          className: "SearchResultPoiOpeningHours"
        }
      }
    }
  }
};

export const SearchResultPoiCategorySet: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultPoiCategorySet",
    modelProperties: {
      id: {
        serializedName: "id",
        readOnly: true,
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const SearchResultPoiClassification: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultPoiClassification",
    modelProperties: {
      code: {
        serializedName: "code",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      names: {
        serializedName: "names",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchResultPoiClassificationName"
            }
          }
        }
      }
    }
  }
};

export const SearchResultPoiClassificationName: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultPoiClassificationName",
    modelProperties: {
      nameLocale: {
        serializedName: "nameLocale",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      name: {
        serializedName: "name",
        readOnly: true,
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SearchResultPoiBrand: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultPoiBrand",
    modelProperties: {
      name: {
        serializedName: "name",
        readOnly: true,
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SearchResultPoiOpeningHours: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultPoiOpeningHours",
    modelProperties: {
      mode: {
        serializedName: "mode",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      timeRanges: {
        serializedName: "timeRanges",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchResultPoiOpeningHoursTimeRange"
            }
          }
        }
      }
    }
  }
};

export const SearchResultPoiOpeningHoursTimeRange: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultPoiOpeningHoursTimeRange",
    modelProperties: {
      startTime: {
        serializedName: "startTime",
        type: {
          name: "Composite",
          className: "SearchResultPoiOpeningHoursTimeRangeTime"
        }
      },
      endTime: {
        serializedName: "endTime",
        type: {
          name: "Composite",
          className: "SearchResultPoiOpeningHoursTimeRangeTime"
        }
      }
    }
  }
};

export const SearchResultPoiOpeningHoursTimeRangeTime: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultPoiOpeningHoursTimeRangeTime",
    modelProperties: {
      date: {
        serializedName: "date",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      hour: {
        serializedName: "hour",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      minute: {
        serializedName: "minute",
        readOnly: true,
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const SearchResultAddress: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultAddress",
    modelProperties: {
      buildingNumber: {
        serializedName: "buildingNumber",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      street: {
        serializedName: "street",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      crossStreet: {
        serializedName: "crossStreet",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      streetNumber: {
        serializedName: "streetNumber",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      routeNumbers: {
        serializedName: "routeNumbers",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      },
      streetName: {
        serializedName: "streetName",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      streetNameAndNumber: {
        serializedName: "streetNameAndNumber",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      municipality: {
        serializedName: "municipality",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      municipalitySubdivision: {
        serializedName: "municipalitySubdivision",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      countryTertiarySubdivision: {
        serializedName: "countryTertiarySubdivision",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      countrySecondarySubdivision: {
        serializedName: "countrySecondarySubdivision",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      countrySubdivision: {
        serializedName: "countrySubdivision",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      postalCode: {
        serializedName: "postalCode",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      extendedPostalCode: {
        serializedName: "extendedPostalCode",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      countryCode: {
        serializedName: "countryCode",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      country: {
        serializedName: "country",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      countryCodeISO3: {
        serializedName: "countryCodeISO3",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      freeformAddress: {
        serializedName: "freeformAddress",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      countrySubdivisionName: {
        serializedName: "countrySubdivisionName",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      localName: {
        serializedName: "localName",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      boundingBox: {
        serializedName: "boundingBox",
        readOnly: true,
        type: {
          name: "Dictionary",
          value: { type: { name: "any" } }
        }
      }
    }
  }
};

export const SearchResultViewport: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultViewport",
    modelProperties: {
      topLeftPoint: {
        serializedName: "topLeftPoint",
        type: {
          name: "Composite",
          className: "CoordinatesPairAbbreviated"
        }
      },
      btmRightPoint: {
        serializedName: "btmRightPoint",
        type: {
          name: "Composite",
          className: "CoordinatesPairAbbreviated"
        }
      }
    }
  }
};

export const SearchResultEntryPoint: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultEntryPoint",
    modelProperties: {
      type: {
        serializedName: "type",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      position: {
        serializedName: "position",
        type: {
          name: "Composite",
          className: "CoordinatesPairAbbreviated"
        }
      }
    }
  }
};

export const SearchResultAddressRanges: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchResultAddressRanges",
    modelProperties: {
      rangeLeft: {
        serializedName: "rangeLeft",
        type: {
          name: "String"
        }
      },
      rangeRight: {
        serializedName: "rangeRight",
        type: {
          name: "String"
        }
      },
      from: {
        serializedName: "from",
        type: {
          name: "Composite",
          className: "CoordinatesPairAbbreviated"
        }
      },
      to: {
        serializedName: "to",
        type: {
          name: "Composite",
          className: "CoordinatesPairAbbreviated"
        }
      }
    }
  }
};

export const DataSources: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "DataSources",
    modelProperties: {
      geometry: {
        serializedName: "geometry",
        type: {
          name: "Composite",
          className: "DataSourcesGeometry"
        }
      }
    }
  }
};

export const DataSourcesGeometry: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "DataSourcesGeometry",
    modelProperties: {
      id: {
        serializedName: "id",
        readOnly: true,
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SearchPoiCategoryTreeResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchPoiCategoryTreeResponse",
    modelProperties: {
      poiCategories: {
        serializedName: "poiCategories",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "PoiCategoryResult"
            }
          }
        }
      }
    }
  }
};

export const PoiCategoryResult: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "PoiCategoryResult",
    modelProperties: {
      id: {
        serializedName: "id",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      childCategoryIds: {
        serializedName: "childCategoryIds",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      },
      synonyms: {
        serializedName: "synonyms",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const SearchAddressReverseResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressReverseResponse",
    modelProperties: {
      summary: {
        serializedName: "summary",
        type: {
          name: "Composite",
          className: "SearchCommonSummary"
        }
      },
      addresses: {
        serializedName: "addresses",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchAddressReverseResult"
            }
          }
        }
      }
    }
  }
};

export const SearchAddressReverseResult: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressReverseResult",
    modelProperties: {
      address: {
        serializedName: "address",
        type: {
          name: "Composite",
          className: "SearchResultAddress"
        }
      },
      position: {
        serializedName: "position",
        readOnly: true,
        type: {
          name: "String"
        }
      },
      matchType: {
        serializedName: "matchType",
        readOnly: true,
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SearchAddressReverseCrossStreetResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressReverseCrossStreetResponse",
    modelProperties: {
      summary: {
        serializedName: "summary",
        type: {
          name: "Composite",
          className: "SearchCommonSummary"
        }
      },
      addresses: {
        serializedName: "addresses",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchAddressReverseCrossStreetResult"
            }
          }
        }
      }
    }
  }
};

export const SearchAddressReverseCrossStreetResult: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressReverseCrossStreetResult",
    modelProperties: {
      address: {
        serializedName: "address",
        type: {
          name: "Composite",
          className: "SearchResultAddress"
        }
      },
      position: {
        serializedName: "position",
        readOnly: true,
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SearchInsideGeometryRequestBody: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchInsideGeometryRequestBody",
    modelProperties: {
      geometry: {
        serializedName: "geometry",
        type: {
          name: "Dictionary",
          value: { type: { name: "any" } }
        }
      }
    }
  }
};

export const SearchAlongRouteRequestBody: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAlongRouteRequestBody",
    modelProperties: {
      route: {
        serializedName: "route",
        type: {
          name: "Composite",
          className: "GeoJsonLineString"
        }
      }
    }
  }
};

export const GeoJsonLineStringData: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonLineStringData",
    modelProperties: {
      coordinates: {
        serializedName: "coordinates",
        required: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "Number"
                }
              }
            }
          }
        }
      }
    }
  }
};

export const BatchRequestBody: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "BatchRequestBody",
    modelProperties: {
      batchItems: {
        serializedName: "batchItems",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "BatchRequestBodyBatchItemsItem"
            }
          }
        }
      }
    }
  }
};

export const BatchRequestBodyBatchItemsItem: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "BatchRequestBodyBatchItemsItem",
    modelProperties: {
      query: {
        serializedName: "query",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BatchResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "BatchResponse",
    modelProperties: {
      summary: {
        serializedName: "summary",
        type: {
          name: "Composite",
          className: "BatchResponseSummary"
        }
      }
    }
  }
};

export const BatchResponseSummary: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "BatchResponseSummary",
    modelProperties: {
      successfulRequests: {
        serializedName: "successfulRequests",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      totalRequests: {
        serializedName: "totalRequests",
        readOnly: true,
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const BatchItem: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "BatchItem",
    modelProperties: {
      statusCode: {
        serializedName: "statusCode",
        readOnly: true,
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const SearchSummaryGeoBias: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchSummaryGeoBias",
    modelProperties: {
      lat: {
        serializedName: "lat",
        readOnly: true,
        type: {
          name: "Number"
        }
      },
      lon: {
        serializedName: "lon",
        readOnly: true,
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const GeoJsonPointData: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonPointData",
    modelProperties: {
      coordinates: {
        serializedName: "coordinates",
        required: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Number"
            }
          }
        }
      }
    }
  }
};

export const GeoJsonMultiPointData: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonMultiPointData",
    modelProperties: {
      coordinates: {
        serializedName: "coordinates",
        required: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "Number"
                }
              }
            }
          }
        }
      }
    }
  }
};

export const GeoJsonMultiLineStringData: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonMultiLineStringData",
    modelProperties: {
      coordinates: {
        serializedName: "coordinates",
        required: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "Sequence",
                  element: {
                    type: {
                      name: "Number"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

export const GeoJsonPolygonData: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonPolygonData",
    modelProperties: {
      coordinates: {
        serializedName: "coordinates",
        required: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "Sequence",
                  element: {
                    type: {
                      name: "Number"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

export const GeoJsonMultiPolygonData: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonMultiPolygonData",
    modelProperties: {
      coordinates: {
        serializedName: "coordinates",
        required: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "Sequence",
                  element: {
                    type: {
                      name: "Sequence",
                      element: {
                        type: {
                          name: "Number"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

export const GeoJsonGeometryCollectionData: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonGeometryCollectionData",
    modelProperties: {
      geometries: {
        serializedName: "geometries",
        required: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "GeoJsonGeometry"
            }
          }
        }
      }
    }
  }
};

export const GeoJsonFeatureData: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonFeatureData",
    modelProperties: {
      geometry: {
        serializedName: "geometry",
        type: {
          name: "Composite",
          className: "GeoJsonGeometry"
        }
      },
      properties: {
        serializedName: "properties",
        type: {
          name: "Dictionary",
          value: { type: { name: "any" } }
        }
      },
      id: {
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      featureType: {
        serializedName: "featureType",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GeoJsonFeatureCollectionData: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "GeoJsonFeatureCollectionData",
    modelProperties: {
      features: {
        serializedName: "features",
        required: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "GeoJsonFeature"
            }
          }
        }
      }
    }
  }
};

export const GeoJsonGeometry: coreClient.CompositeMapper = {
  serializedName: "GeoJsonGeometry",
  type: {
    name: "Composite",
    className: "GeoJsonGeometry",
    uberParent: "GeoJsonObject",
    polymorphicDiscriminator: {
      serializedName: "type",
      clientName: "type"
    },
    modelProperties: {
      ...GeoJsonObject.type.modelProperties
    }
  }
};

export const GeoJsonFeature: coreClient.CompositeMapper = {
  serializedName: "Feature",
  type: {
    name: "Composite",
    className: "GeoJsonFeature",
    uberParent: "GeoJsonObject",
    polymorphicDiscriminator: GeoJsonObject.type.polymorphicDiscriminator,
    modelProperties: {
      ...GeoJsonObject.type.modelProperties,
      ...GeoJsonFeatureData.type.modelProperties
    }
  }
};

export const GeoJsonFeatureCollection: coreClient.CompositeMapper = {
  serializedName: "FeatureCollection",
  type: {
    name: "Composite",
    className: "GeoJsonFeatureCollection",
    uberParent: "GeoJsonObject",
    polymorphicDiscriminator: GeoJsonObject.type.polymorphicDiscriminator,
    modelProperties: {
      ...GeoJsonObject.type.modelProperties,
      ...GeoJsonFeatureCollectionData.type.modelProperties
    }
  }
};

export const SearchFuzzyBatchItemResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchFuzzyBatchItemResponse",
    modelProperties: {
      ...SearchCommonResponse.type.modelProperties,
      ...ErrorResponse.type.modelProperties
    }
  }
};

export const SearchAddressBatchItemResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressBatchItemResponse",
    modelProperties: {
      ...SearchCommonResponse.type.modelProperties,
      ...ErrorResponse.type.modelProperties
    }
  }
};

export const SearchAddressReverseBatchItemResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressReverseBatchItemResponse",
    modelProperties: {
      ...SearchAddressReverseResponse.type.modelProperties,
      ...ErrorResponse.type.modelProperties
    }
  }
};

export const SearchCommonSummaryGeoBias: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchCommonSummaryGeoBias",
    modelProperties: {
      ...CoordinatesPairAbbreviated.type.modelProperties
    }
  }
};

export const GeoJsonLineString: coreClient.CompositeMapper = {
  serializedName: "LineString",
  type: {
    name: "Composite",
    className: "GeoJsonLineString",
    uberParent: "GeoJsonLineStringData",
    polymorphicDiscriminator:
      GeoJsonLineStringData.type.polymorphicDiscriminator,
    modelProperties: {
      ...GeoJsonGeometry.type.modelProperties,
      ...GeoJsonLineStringData.type.modelProperties
    }
  }
};

export const SearchFuzzyBatchResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchFuzzyBatchResponse",
    modelProperties: {
      ...BatchResponse.type.modelProperties,
      batchItems: {
        serializedName: "batchItems",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchFuzzyBatchItem"
            }
          }
        }
      }
    }
  }
};

export const SearchAddressBatchResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressBatchResponse",
    modelProperties: {
      ...BatchResponse.type.modelProperties,
      batchItems: {
        serializedName: "batchItems",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchAddressBatchItem"
            }
          }
        }
      }
    }
  }
};

export const SearchAddressReverseBatchResponse: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressReverseBatchResponse",
    modelProperties: {
      ...BatchResponse.type.modelProperties,
      batchItems: {
        serializedName: "batchItems",
        readOnly: true,
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "SearchAddressReverseBatchItem"
            }
          }
        }
      }
    }
  }
};

export const SearchFuzzyBatchItem: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchFuzzyBatchItem",
    modelProperties: {
      ...BatchItem.type.modelProperties,
      response: {
        serializedName: "response",
        type: {
          name: "Composite",
          className: "SearchFuzzyBatchItemResponse"
        }
      }
    }
  }
};

export const SearchAddressBatchItem: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressBatchItem",
    modelProperties: {
      ...BatchItem.type.modelProperties,
      response: {
        serializedName: "response",
        type: {
          name: "Composite",
          className: "SearchAddressBatchItemResponse"
        }
      }
    }
  }
};

export const SearchAddressReverseBatchItem: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchAddressReverseBatchItem",
    modelProperties: {
      ...BatchItem.type.modelProperties,
      response: {
        serializedName: "response",
        type: {
          name: "Composite",
          className: "SearchAddressReverseBatchItemResponse"
        }
      }
    }
  }
};

export const GeoJsonPoint: coreClient.CompositeMapper = {
  serializedName: "Point",
  type: {
    name: "Composite",
    className: "GeoJsonPoint",
    uberParent: "GeoJsonPointData",
    polymorphicDiscriminator: GeoJsonPointData.type.polymorphicDiscriminator,
    modelProperties: {
      ...GeoJsonGeometry.type.modelProperties,
      ...GeoJsonPointData.type.modelProperties
    }
  }
};

export const GeoJsonMultiPoint: coreClient.CompositeMapper = {
  serializedName: "MultiPoint",
  type: {
    name: "Composite",
    className: "GeoJsonMultiPoint",
    uberParent: "GeoJsonMultiPointData",
    polymorphicDiscriminator:
      GeoJsonMultiPointData.type.polymorphicDiscriminator,
    modelProperties: {
      ...GeoJsonGeometry.type.modelProperties,
      ...GeoJsonMultiPointData.type.modelProperties
    }
  }
};

export const GeoJsonMultiLineString: coreClient.CompositeMapper = {
  serializedName: "MultiLineString",
  type: {
    name: "Composite",
    className: "GeoJsonMultiLineString",
    uberParent: "GeoJsonMultiLineStringData",
    polymorphicDiscriminator:
      GeoJsonMultiLineStringData.type.polymorphicDiscriminator,
    modelProperties: {
      ...GeoJsonGeometry.type.modelProperties,
      ...GeoJsonMultiLineStringData.type.modelProperties
    }
  }
};

export const GeoJsonPolygon: coreClient.CompositeMapper = {
  serializedName: "Polygon",
  type: {
    name: "Composite",
    className: "GeoJsonPolygon",
    uberParent: "GeoJsonPolygonData",
    polymorphicDiscriminator: GeoJsonPolygonData.type.polymorphicDiscriminator,
    modelProperties: {
      ...GeoJsonGeometry.type.modelProperties,
      ...GeoJsonPolygonData.type.modelProperties
    }
  }
};

export const GeoJsonMultiPolygon: coreClient.CompositeMapper = {
  serializedName: "MultiPolygon",
  type: {
    name: "Composite",
    className: "GeoJsonMultiPolygon",
    uberParent: "GeoJsonMultiPolygonData",
    polymorphicDiscriminator:
      GeoJsonMultiPolygonData.type.polymorphicDiscriminator,
    modelProperties: {
      ...GeoJsonGeometry.type.modelProperties,
      ...GeoJsonMultiPolygonData.type.modelProperties
    }
  }
};

export const GeoJsonGeometryCollection: coreClient.CompositeMapper = {
  serializedName: "GeometryCollection",
  type: {
    name: "Composite",
    className: "GeoJsonGeometryCollection",
    uberParent: "GeoJsonGeometryCollectionData",
    polymorphicDiscriminator:
      GeoJsonGeometryCollectionData.type.polymorphicDiscriminator,
    modelProperties: {
      ...GeoJsonGeometry.type.modelProperties,
      ...GeoJsonGeometryCollectionData.type.modelProperties
    }
  }
};

export const SearchPostSearchFuzzyBatchHeaders: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchPostSearchFuzzyBatchHeaders",
    modelProperties: {
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SearchPostSearchAddressBatchHeaders: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchPostSearchAddressBatchHeaders",
    modelProperties: {
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SearchPostSearchAddressReverseBatchHeaders: coreClient.CompositeMapper = {
  type: {
    name: "Composite",
    className: "SearchPostSearchAddressReverseBatchHeaders",
    modelProperties: {
      location: {
        serializedName: "location",
        type: {
          name: "String"
        }
      }
    }
  }
};

export let discriminators = {
  GeoJsonObject: GeoJsonObject,
  "GeoJsonObject.GeoJsonGeometry": GeoJsonGeometry,
  "GeoJsonObject.Feature": GeoJsonFeature,
  "GeoJsonObject.FeatureCollection": GeoJsonFeatureCollection,
  "GeoJsonLineStringData.LineString": GeoJsonLineString,
  "GeoJsonPointData.Point": GeoJsonPoint,
  "GeoJsonMultiPointData.MultiPoint": GeoJsonMultiPoint,
  "GeoJsonMultiLineStringData.MultiLineString": GeoJsonMultiLineString,
  "GeoJsonPolygonData.Polygon": GeoJsonPolygon,
  "GeoJsonMultiPolygonData.MultiPolygon": GeoJsonMultiPolygon,
  "GeoJsonGeometryCollectionData.GeometryCollection": GeoJsonGeometryCollection
};
