/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  OperationParameter,
  OperationURLParameter,
  OperationQueryParameter
} from "@azure/core-client";
import {
  SearchInsideGeometryRequestBody as SearchInsideGeometryRequestBodyMapper,
  SearchAlongRouteRequestBody as SearchAlongRouteRequestBodyMapper,
  BatchRequestBody as BatchRequestBodyMapper
} from "../models/mappers";

export const accept: OperationParameter = {
  parameterPath: "accept",
  mapper: {
    defaultValue: "application/json",
    isConstant: true,
    serializedName: "Accept",
    type: {
      name: "String"
    }
  }
};

export const geography: OperationURLParameter = {
  parameterPath: "geography",
  mapper: {
    serializedName: "geography",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const xMsClientId: OperationParameter = {
  parameterPath: "xMsClientId",
  mapper: {
    serializedName: "x-ms-client-id",
    type: {
      name: "String"
    }
  }
};

export const apiVersion: OperationQueryParameter = {
  parameterPath: "apiVersion",
  mapper: {
    defaultValue: "1.0",
    isConstant: true,
    serializedName: "api-version",
    type: {
      name: "String"
    }
  }
};

export const format: OperationURLParameter = {
  parameterPath: "format",
  mapper: {
    serializedName: "format",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const geometries: OperationQueryParameter = {
  parameterPath: "geometries",
  mapper: {
    serializedName: "geometries",
    required: true,
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "String"
        }
      }
    }
  },
  collectionFormat: "CSV"
};

export const format1: OperationURLParameter = {
  parameterPath: "format",
  mapper: {
    serializedName: "format",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const query: OperationQueryParameter = {
  parameterPath: "query",
  mapper: {
    serializedName: "query",
    required: true,
    type: {
      name: "String"
    }
  }
};

export const typeahead: OperationQueryParameter = {
  parameterPath: ["options", "typeahead"],
  mapper: {
    serializedName: "typeahead",
    type: {
      name: "Boolean"
    }
  }
};

export const limit: OperationQueryParameter = {
  parameterPath: ["options", "limit"],
  mapper: {
    constraints: {
      InclusiveMaximum: 100,
      InclusiveMinimum: 1
    },
    serializedName: "limit",
    type: {
      name: "Number"
    }
  }
};

export const ofs: OperationQueryParameter = {
  parameterPath: ["options", "ofs"],
  mapper: {
    constraints: {
      InclusiveMaximum: 1900,
      InclusiveMinimum: 0
    },
    serializedName: "ofs",
    type: {
      name: "Number"
    }
  }
};

export const categorySet: OperationQueryParameter = {
  parameterPath: ["options", "categorySet"],
  mapper: {
    serializedName: "categorySet",
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "Number"
        }
      }
    }
  },
  collectionFormat: "CSV"
};

export const countrySet: OperationQueryParameter = {
  parameterPath: ["options", "countrySet"],
  mapper: {
    serializedName: "countrySet",
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "String"
        }
      }
    }
  },
  collectionFormat: "CSV"
};

export const lat: OperationQueryParameter = {
  parameterPath: ["options", "lat"],
  mapper: {
    serializedName: "lat",
    type: {
      name: "Number"
    }
  }
};

export const lon: OperationQueryParameter = {
  parameterPath: ["options", "lon"],
  mapper: {
    serializedName: "lon",
    type: {
      name: "Number"
    }
  }
};

export const radius: OperationQueryParameter = {
  parameterPath: ["options", "radius"],
  mapper: {
    serializedName: "radius",
    type: {
      name: "Number"
    }
  }
};

export const topLeft: OperationQueryParameter = {
  parameterPath: ["options", "topLeft"],
  mapper: {
    serializedName: "topLeft",
    type: {
      name: "String"
    }
  }
};

export const btmRight: OperationQueryParameter = {
  parameterPath: ["options", "btmRight"],
  mapper: {
    serializedName: "btmRight",
    type: {
      name: "String"
    }
  }
};

export const language: OperationQueryParameter = {
  parameterPath: ["options", "language"],
  mapper: {
    serializedName: "language",
    type: {
      name: "String"
    }
  }
};

export const extendedPostalCodesFor: OperationQueryParameter = {
  parameterPath: ["options", "extendedPostalCodesFor"],
  mapper: {
    serializedName: "extendedPostalCodesFor",
    type: {
      name: "String"
    }
  }
};

export const minFuzzyLevel: OperationQueryParameter = {
  parameterPath: ["options", "minFuzzyLevel"],
  mapper: {
    constraints: {
      InclusiveMaximum: 4,
      InclusiveMinimum: 1
    },
    serializedName: "minFuzzyLevel",
    type: {
      name: "Number"
    }
  }
};

export const maxFuzzyLevel: OperationQueryParameter = {
  parameterPath: ["options", "maxFuzzyLevel"],
  mapper: {
    constraints: {
      InclusiveMaximum: 4,
      InclusiveMinimum: 1
    },
    serializedName: "maxFuzzyLevel",
    type: {
      name: "Number"
    }
  }
};

export const idxSet: OperationQueryParameter = {
  parameterPath: ["options", "idxSet"],
  mapper: {
    serializedName: "idxSet",
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "String"
        }
      }
    }
  },
  collectionFormat: "CSV"
};

export const brandSet: OperationQueryParameter = {
  parameterPath: ["options", "brandSet"],
  mapper: {
    serializedName: "brandSet",
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "String"
        }
      }
    }
  },
  collectionFormat: "CSV"
};

export const connectorSet: OperationQueryParameter = {
  parameterPath: ["options", "connectorSet"],
  mapper: {
    serializedName: "connectorSet",
    type: {
      name: "Sequence",
      element: {
        type: {
          name: "String"
        }
      }
    }
  },
  collectionFormat: "CSV"
};

export const view: OperationQueryParameter = {
  parameterPath: ["options", "view"],
  mapper: {
    serializedName: "view",
    type: {
      name: "String"
    }
  }
};

export const openingHours: OperationQueryParameter = {
  parameterPath: ["options", "openingHours"],
  mapper: {
    serializedName: "openingHours",
    type: {
      name: "String"
    }
  }
};

export const lat1: OperationQueryParameter = {
  parameterPath: "lat",
  mapper: {
    serializedName: "lat",
    required: true,
    type: {
      name: "Number"
    }
  }
};

export const lon1: OperationQueryParameter = {
  parameterPath: "lon",
  mapper: {
    serializedName: "lon",
    required: true,
    type: {
      name: "Number"
    }
  }
};

export const returnSpeedLimit: OperationQueryParameter = {
  parameterPath: ["options", "returnSpeedLimit"],
  mapper: {
    serializedName: "returnSpeedLimit",
    type: {
      name: "Boolean"
    }
  }
};

export const heading: OperationQueryParameter = {
  parameterPath: ["options", "heading"],
  mapper: {
    constraints: {
      InclusiveMaximum: 360,
      InclusiveMinimum: -360
    },
    serializedName: "heading",
    type: {
      name: "Number"
    }
  }
};

export const numberParam: OperationQueryParameter = {
  parameterPath: ["options", "numberParam"],
  mapper: {
    serializedName: "number",
    type: {
      name: "String"
    }
  }
};

export const returnRoadUse: OperationQueryParameter = {
  parameterPath: ["options", "returnRoadUse"],
  mapper: {
    serializedName: "returnRoadUse",
    type: {
      name: "Boolean"
    }
  }
};

export const roadUse: OperationQueryParameter = {
  parameterPath: ["options", "roadUse"],
  mapper: {
    serializedName: "roadUse",
    type: {
      name: "String"
    }
  }
};

export const allowFreeformNewline: OperationQueryParameter = {
  parameterPath: ["options", "allowFreeformNewline"],
  mapper: {
    serializedName: "allowFreeformNewline",
    type: {
      name: "Boolean"
    }
  }
};

export const returnMatchType: OperationQueryParameter = {
  parameterPath: ["options", "returnMatchType"],
  mapper: {
    serializedName: "returnMatchType",
    type: {
      name: "Boolean"
    }
  }
};

export const entityType: OperationQueryParameter = {
  parameterPath: ["options", "entityType"],
  mapper: {
    serializedName: "entityType",
    type: {
      name: "String"
    }
  }
};

export const countryCode: OperationQueryParameter = {
  parameterPath: ["options", "countryCode"],
  mapper: {
    defaultValue: "US",
    serializedName: "countryCode",
    type: {
      name: "String"
    }
  }
};

export const streetNumber: OperationQueryParameter = {
  parameterPath: ["options", "streetNumber"],
  mapper: {
    serializedName: "streetNumber",
    type: {
      name: "String"
    }
  }
};

export const streetName: OperationQueryParameter = {
  parameterPath: ["options", "streetName"],
  mapper: {
    serializedName: "streetName",
    type: {
      name: "String"
    }
  }
};

export const crossStreet: OperationQueryParameter = {
  parameterPath: ["options", "crossStreet"],
  mapper: {
    serializedName: "crossStreet",
    type: {
      name: "String"
    }
  }
};

export const municipality: OperationQueryParameter = {
  parameterPath: ["options", "municipality"],
  mapper: {
    serializedName: "municipality",
    type: {
      name: "String"
    }
  }
};

export const municipalitySubdivision: OperationQueryParameter = {
  parameterPath: ["options", "municipalitySubdivision"],
  mapper: {
    serializedName: "municipalitySubdivision",
    type: {
      name: "String"
    }
  }
};

export const countryTertiarySubdivision: OperationQueryParameter = {
  parameterPath: ["options", "countryTertiarySubdivision"],
  mapper: {
    serializedName: "countryTertiarySubdivision",
    type: {
      name: "String"
    }
  }
};

export const countrySecondarySubdivision: OperationQueryParameter = {
  parameterPath: ["options", "countrySecondarySubdivision"],
  mapper: {
    serializedName: "countrySecondarySubdivision",
    type: {
      name: "String"
    }
  }
};

export const countrySubdivision: OperationQueryParameter = {
  parameterPath: ["options", "countrySubdivision"],
  mapper: {
    serializedName: "countrySubdivision",
    type: {
      name: "String"
    }
  }
};

export const postalCode: OperationQueryParameter = {
  parameterPath: ["options", "postalCode"],
  mapper: {
    serializedName: "postalCode",
    type: {
      name: "String"
    }
  }
};

export const contentType: OperationParameter = {
  parameterPath: ["options", "contentType"],
  mapper: {
    defaultValue: "application/json",
    isConstant: true,
    serializedName: "Content-Type",
    type: {
      name: "String"
    }
  }
};

export const searchInsideGeometryRequestBody: OperationParameter = {
  parameterPath: "searchInsideGeometryRequestBody",
  mapper: SearchInsideGeometryRequestBodyMapper
};

export const searchAlongRouteRequestBody: OperationParameter = {
  parameterPath: "searchAlongRouteRequestBody",
  mapper: SearchAlongRouteRequestBodyMapper
};

export const maxDetourTime: OperationQueryParameter = {
  parameterPath: "maxDetourTime",
  mapper: {
    constraints: {
      InclusiveMaximum: 3600
    },
    serializedName: "maxDetourTime",
    required: true,
    type: {
      name: "Number"
    }
  }
};

export const limit1: OperationQueryParameter = {
  parameterPath: ["options", "limit"],
  mapper: {
    constraints: {
      InclusiveMaximum: 20
    },
    serializedName: "limit",
    type: {
      name: "Number"
    }
  }
};

export const searchFuzzyBatchRequestBody: OperationParameter = {
  parameterPath: "searchFuzzyBatchRequestBody",
  mapper: BatchRequestBodyMapper
};

export const searchAddressBatchRequestBody: OperationParameter = {
  parameterPath: "searchAddressBatchRequestBody",
  mapper: BatchRequestBodyMapper
};

export const searchAddressReverseBatchRequestBody: OperationParameter = {
  parameterPath: "searchAddressReverseBatchRequestBody",
  mapper: BatchRequestBodyMapper
};
