/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreAuth from "@azure/core-auth";
import { TimezoneImpl } from "./operations";
import { Timezone } from "./operationsInterfaces";
import { TimezoneClientContext } from "./timezoneClientContext";
import { TimezoneClientOptionalParams } from "./models";

export class TimezoneClient extends TimezoneClientContext {
  /**
   * Initializes a new instance of the TimezoneClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param options The parameter options
   */
  constructor(
    credentials: coreAuth.TokenCredential,
    options?: TimezoneClientOptionalParams
  ) {
    super(credentials, options);
    this.timezone = new TimezoneImpl(this);
  }

  timezone: Timezone;
}
