/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as coreClient from "@azure/core-client";

/** Common error response for all Azure Resource Manager APIs to return error details for failed operations. (This also follows the OData error response format.). */
export interface ErrorResponse {
  /** The error object. */
  error?: ErrorDetail;
}

/** The error detail. */
export interface ErrorDetail {
  /**
   * The error code.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly code?: string;
  /**
   * The error message.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly message?: string;
  /**
   * The error target.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly target?: string;
  /**
   * The error details.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly details?: ErrorDetail[];
  /**
   * The error additional info.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly additionalInfo?: ErrorAdditionalInfo[];
}

/** The resource management error additional info. */
export interface ErrorAdditionalInfo {
  /**
   * The additional info type.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly type?: string;
  /**
   * The additional info.
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly info?: Record<string, unknown>;
}

/** This object is returned from a successful Get Copyright Caption call */
export interface GetCopyrightCaptionResult {
  /**
   * Format Version property
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly formatVersion?: string;
  /**
   * Copyrights Caption property
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly copyrightsCaption?: string;
}

/** This object is returned from a successful Get Copyright From Bounding Box call */
export interface GetCopyrightFromBoundingBoxResult {
  /**
   * Format Version property
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly formatVersion?: string;
  /**
   * General Copyrights array
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly generalCopyrights?: string[];
  /**
   * Regions array
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly regions?: RegionCopyrights[];
}

export interface RegionCopyrights {
  /**
   * Copyrights array
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly copyrights?: string[];
  /**
   * Country property
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly country?: RegionCopyrightsCountry;
}

/** Country property */
export interface RegionCopyrightsCountry {
  /**
   * ISO3 property
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly iso3?: string;
  /**
   * Label property
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly label?: string;
}

/** This object is returned from a successful Get Copyright For Tile call */
export interface GetCopyrightForTileResult {
  /**
   * Format Version property
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly formatVersion?: string;
  /**
   * General Copyrights array
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly generalCopyrights?: string[];
  /**
   * Regions array
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly regions?: RegionCopyrights[];
}

/** This object is returned from a successful Get Copyright For World call */
export interface GetCopyrightForWorldResult {
  /**
   * Format Version property
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly formatVersion?: string;
  /**
   * General Copyrights array
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly generalCopyrights?: string[];
  /**
   * Regions array
   * NOTE: This property will not be serialized. It can only be populated by the server.
   */
  readonly regions?: RegionCopyrights[];
}

/** Defines headers for Render_getMapStaticImage operation. */
export interface RenderGetMapStaticImageHeaders {
  /** The content-type for the response. */
  contentType?: string;
}

/** Defines headers for Render_getMapTile operation. */
export interface RenderGetMapTileHeaders {
  /** The content-type for the response. */
  contentType?: string;
}

/** Defines headers for Render_getMapStateTilePreview operation. */
export interface RenderGetMapStateTilePreviewHeaders {
  /** The content-type for the response. */
  contentType?: string;
}

/** Defines headers for Render_getMapImageryTile operation. */
export interface RenderGetMapImageryTileHeaders {
  /** The content-type for the response. */
  contentType?: string;
}

/** Defines headers for RenderV2_getMapTilePreview operation. */
export interface RenderV2GetMapTilePreviewHeaders {
  /** The content-type for the response. */
  contentType?: string;
}

/** Known values of {@link Geography} that the service accepts. */
export const enum KnownGeography {
  Us = "us",
  Eu = "eu"
}

/**
 * Defines values for Geography. \
 * {@link KnownGeography} can be used interchangeably with Geography,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **us** \
 * **eu**
 */
export type Geography = string;

/** Known values of {@link RasterTileFormat} that the service accepts. */
export const enum KnownRasterTileFormat {
  /** An image in the png format. Supports zoom levels 0 through 18. */
  Png = "png"
}

/**
 * Defines values for RasterTileFormat. \
 * {@link KnownRasterTileFormat} can be used interchangeably with RasterTileFormat,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **png**: An image in the png format. Supports zoom levels 0 through 18.
 */
export type RasterTileFormat = string;

/** Known values of {@link StaticMapLayer} that the service accepts. */
export const enum KnownStaticMapLayer {
  /** Returns an image containing all map features including polygons, borders, roads and labels. */
  Basic = "basic",
  /** Returns an image containing borders, roads, and labels, and can be overlaid on other tiles (such as satellite imagery) to produce hybrid tiles. */
  Hybrid = "hybrid",
  /** Returns an image of just the map's label information. */
  Labels = "labels"
}

/**
 * Defines values for StaticMapLayer. \
 * {@link KnownStaticMapLayer} can be used interchangeably with StaticMapLayer,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **basic**: Returns an image containing all map features including polygons, borders, roads and labels. \
 * **hybrid**: Returns an image containing borders, roads, and labels, and can be overlaid on other tiles (such as satellite imagery) to produce hybrid tiles. \
 * **labels**: Returns an image of just the map's label information.
 */
export type StaticMapLayer = string;

/** Known values of {@link MapImageStyle} that the service accepts. */
export const enum KnownMapImageStyle {
  /** Azure Maps main style */
  Main = "main",
  /** Dark grey version of the Azure Maps main style */
  Dark = "dark"
}

/**
 * Defines values for MapImageStyle. \
 * {@link KnownMapImageStyle} can be used interchangeably with MapImageStyle,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **main**: Azure Maps main style \
 * **dark**: Dark grey version of the Azure Maps main style
 */
export type MapImageStyle = string;

/** Known values of {@link TileFormat} that the service accepts. */
export const enum KnownTileFormat {
  /** An image in the png format. Supports zoom levels 0 through 18. */
  Png = "png",
  /** Vector graphic in the pbf format. Supports zoom levels 0 through 22. */
  Pbf = "pbf"
}

/**
 * Defines values for TileFormat. \
 * {@link KnownTileFormat} can be used interchangeably with TileFormat,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **png**: An image in the png format. Supports zoom levels 0 through 18. \
 * **pbf**: Vector graphic in the pbf format. Supports zoom levels 0 through 22.
 */
export type TileFormat = string;

/** Known values of {@link MapTileLayer} that the service accepts. */
export const enum KnownMapTileLayer {
  /** Returns a tile containing all map features including polygons, borders, roads and labels. */
  Basic = "basic",
  /** Returns a tile containing borders, roads, and labels, and can be overlaid on other tiles (such as satellite imagery) to produce hybrid tiles. */
  Hybrid = "hybrid",
  /** Returns a tile of just the map's label information. */
  Labels = "labels",
  /** Map canvas complete with shaded relief tiles. Zoom levels 0-6 (inclusive) are supported. Png is the only supported TileFormat and only available MapTileSize is 512. */
  Terra = "terra"
}

/**
 * Defines values for MapTileLayer. \
 * {@link KnownMapTileLayer} can be used interchangeably with MapTileLayer,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **basic**: Returns a tile containing all map features including polygons, borders, roads and labels. \
 * **hybrid**: Returns a tile containing borders, roads, and labels, and can be overlaid on other tiles (such as satellite imagery) to produce hybrid tiles. \
 * **labels**: Returns a tile of just the map's label information. \
 * **terra**: Map canvas complete with shaded relief tiles. Zoom levels 0-6 (inclusive) are supported. Png is the only supported TileFormat and only available MapTileSize is 512.
 */
export type MapTileLayer = string;

/** Known values of {@link MapTileStyle} that the service accepts. */
export const enum KnownMapTileStyle {
  /** Azure Maps main style */
  Main = "main",
  /** Dark grey version of the Azure Maps main style. PNG is the only supported TileFormat. */
  Dark = "dark",
  /** Azure Maps main style completed with shaded relief. Supported by Layer terra. */
  ShadedRelief = "shaded_relief"
}

/**
 * Defines values for MapTileStyle. \
 * {@link KnownMapTileStyle} can be used interchangeably with MapTileStyle,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **main**: Azure Maps main style \
 * **dark**: Dark grey version of the Azure Maps main style. PNG is the only supported TileFormat. \
 * **shaded_relief**: Azure Maps main style completed with shaded relief. Supported by Layer terra.
 */
export type MapTileStyle = string;

/** Known values of {@link MapTileSize} that the service accepts. */
export const enum KnownMapTileSize {
  /** Return a 256 by 256 pixel tile. */
  TwoHundredFiftySix = "256",
  /** Return a 512 by 512 pixel tile. */
  FiveHundredTwelve = "512"
}

/**
 * Defines values for MapTileSize. \
 * {@link KnownMapTileSize} can be used interchangeably with MapTileSize,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **256**: Return a 256 by 256 pixel tile. \
 * **512**: Return a 512 by 512 pixel tile.
 */
export type MapTileSize = string;

/** Known values of {@link TextFormat} that the service accepts. */
export const enum KnownTextFormat {
  /** [The JavaScript Object Notation Data Interchange Format](https://tools.ietf.org/html/rfc8259) */
  Json = "json",
  /** [The Extensible Markup Language](https://www.w3.org/TR/xml/) */
  Xml = "xml"
}

/**
 * Defines values for TextFormat. \
 * {@link KnownTextFormat} can be used interchangeably with TextFormat,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **json**: [The JavaScript Object Notation Data Interchange Format](https:\/\/tools.ietf.org\/html\/rfc8259) \
 * **xml**: [The Extensible Markup Language](https:\/\/www.w3.org\/TR\/xml\/)
 */
export type TextFormat = string;

/** Known values of {@link MapImageryStyle} that the service accepts. */
export const enum KnownMapImageryStyle {
  /** Satellite imagery */
  Satellite = "satellite"
}

/**
 * Defines values for MapImageryStyle. \
 * {@link KnownMapImageryStyle} can be used interchangeably with MapImageryStyle,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **satellite**: Satellite imagery
 */
export type MapImageryStyle = string;

/** Known values of {@link IncludeText} that the service accepts. */
export const enum KnownIncludeText {
  /** Include all textual data in response. */
  Yes = "yes",
  /** Exclude textual data from response. Only images and country names will be in response. */
  No = "no"
}

/**
 * Defines values for IncludeText. \
 * {@link KnownIncludeText} can be used interchangeably with IncludeText,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **yes**: Include all textual data in response. \
 * **no**: Exclude textual data from response. Only images and country names will be in response.
 */
export type IncludeText = string;

/** Known values of {@link TilesetID} that the service accepts. */
export const enum KnownTilesetID {
  /**
   * A base map is a standard map that displays roads, natural and artificial features along with the labels for those features in a vector tile.<br>
   *
   * Supports zoom levels 0 through 22. Format: vector (pbf).
   */
  MicrosoftBase = "microsoft.base",
  /**
   * Displays labels for roads, natural and artificial features in a vector tile.<br>
   *
   * Supports zoom levels 0 through 22. Format: vector (pbf).
   */
  MicrosoftBaseLabels = "microsoft.base.labels",
  /**
   * Displays road, boundary and label data in a vector tile.<br>
   *
   * Supports zoom levels 0 through 22. Format: vector (pbf).
   */
  MicrosoftBaseHybrid = "microsoft.base.hybrid",
  /**
   * Shaded relief and terra layers.<br>
   *
   * Supports zoom levels 0 through 6. Format: raster (png).
   */
  MicrosoftTerraMain = "microsoft.terra.main",
  /**
   * All layers with our main style.<br>
   *
   * Supports zoom levels 0 through 22. Format: raster (png).
   */
  MicrosoftBaseRoad = "microsoft.base.road",
  /**
   * All layers with our dark grey style.<br>
   *
   * Supports zoom levels 0 through 22. Format: raster (png).
   */
  MicrosoftBaseDarkgrey = "microsoft.base.darkgrey",
  /**
   * Label data in our main style.<br>
   *
   * Supports zoom levels 0 through 22. Format: raster (png).
   */
  MicrosoftBaseLabelsRoad = "microsoft.base.labels.road",
  /**
   * Road, boundary and label data in our main style.<br>
   *
   * Supports zoom levels 0 through 22. Format: raster (png).
   */
  MicrosoftBaseHybridRoad = "microsoft.base.hybrid.road",
  /**
   * A combination of satellite and aerial imagery. Only available in S1 pricing SKU.<br>
   *
   * Supports zoom levels 1 through 19. Format: raster (jpeg).
   */
  MicrosoftImagery = "microsoft.imagery",
  /**
   * Weather radar tiles. Latest weather radar images including areas of rain, snow, ice and mixed conditions. Please see [coverage information](https://aka.ms/AzureMapsWeatherCoverage) for Azure Maps Weather service.  To learn more about the Radar data, please see [Weather concepts](https://aka.ms/AzureMapsWeatherConcepts).<br>
   *
   * Supports zoom levels 0 through 15. Format: raster (png).
   */
  MicrosoftWeatherRadarMain = "microsoft.weather.radar.main",
  /**
   * Weather infrared tiles. Latest Infrared Satellite images shows clouds by their temperature.  Please see [coverage information](https://aka.ms/AzureMapsWeatherCoverage) for Azure Maps Weather service. To learn more about the returned Satellite data, please see [Weather concepts](https://aka.ms/AzureMapsWeatherConcepts).<br>
   *
   * Supports zoom levels 0 through 15. Format: raster (png).
   */
  MicrosoftWeatherInfraredMain = "microsoft.weather.infrared.main",
  /**
   * Digital Elevation Model tiles. The tiles are in the GeoTIFF format with a single 32-bit floating point band. The tiles cover the whole landmass of Earth. Some small islands (e.g., atolls) might not be represented accurately.<br>
   * * The vertical unit for measurement of elevation height is meters. An elevation value of -32767.0 is used for points that have no data value, most often returned where there isn't landmass (i.e. water).<br>
   * * The horizontal reference datum is the World Geodetic System 1984 (WGS84-G1150) and the vertical reference datum is the Earth Gravitational Model 2008 (EGM2008).<br>
   * * Tiles are 258x258 pixel squares rather than the standard 256 x 256. This is done to allow for accurate interpolation of values at the tile edges. As such adjacent tiles overlap by 1 pixel along all edges.<br>
   * * Tile data comes from the [Airbus WorldDEM4Ortho product](https://www.intelligence-airbusds.com/worlddem-streaming/). Urban areas are approximately leveled down to ground level. All other areas are represented by the object surface level (e.g., trees). <br>
   *
   * Supports zoom level 13 only. Format: raster (tiff).
   */
  MicrosoftDem = "microsoft.dem"
}

/**
 * Defines values for TilesetID. \
 * {@link KnownTilesetID} can be used interchangeably with TilesetID,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **microsoft.base**: A base map is a standard map that displays roads, natural and artificial features along with the labels for those features in a vector tile.<br>
 *
 * Supports zoom levels 0 through 22. Format: vector (pbf). \
 * **microsoft.base.labels**: Displays labels for roads, natural and artificial features in a vector tile.<br>
 *
 * Supports zoom levels 0 through 22. Format: vector (pbf). \
 * **microsoft.base.hybrid**: Displays road, boundary and label data in a vector tile.<br>
 *
 * Supports zoom levels 0 through 22. Format: vector (pbf). \
 * **microsoft.terra.main**: Shaded relief and terra layers.<br>
 *
 * Supports zoom levels 0 through 6. Format: raster (png). \
 * **microsoft.base.road**: All layers with our main style.<br>
 *
 * Supports zoom levels 0 through 22. Format: raster (png). \
 * **microsoft.base.darkgrey**: All layers with our dark grey style.<br>
 *
 * Supports zoom levels 0 through 22. Format: raster (png). \
 * **microsoft.base.labels.road**: Label data in our main style.<br>
 *
 * Supports zoom levels 0 through 22. Format: raster (png). \
 * **microsoft.base.hybrid.road**: Road, boundary and label data in our main style.<br>
 *
 * Supports zoom levels 0 through 22. Format: raster (png). \
 * **microsoft.imagery**: A combination of satellite and aerial imagery. Only available in S1 pricing SKU.<br>
 *
 * Supports zoom levels 1 through 19. Format: raster (jpeg). \
 * **microsoft.weather.radar.main**: Weather radar tiles. Latest weather radar images including areas of rain, snow, ice and mixed conditions. Please see [coverage information](https:\/\/aka.ms\/AzureMapsWeatherCoverage) for Azure Maps Weather service.  To learn more about the Radar data, please see [Weather concepts](https:\/\/aka.ms\/AzureMapsWeatherConcepts).<br>
 *
 * Supports zoom levels 0 through 15. Format: raster (png). \
 * **microsoft.weather.infrared.main**: Weather infrared tiles. Latest Infrared Satellite images shows clouds by their temperature.  Please see [coverage information](https:\/\/aka.ms\/AzureMapsWeatherCoverage) for Azure Maps Weather service. To learn more about the returned Satellite data, please see [Weather concepts](https:\/\/aka.ms\/AzureMapsWeatherConcepts).<br>
 *
 * Supports zoom levels 0 through 15. Format: raster (png). \
 * **microsoft.dem**: Digital Elevation Model tiles. The tiles are in the GeoTIFF format with a single 32-bit floating point band. The tiles cover the whole landmass of Earth. Some small islands (e.g., atolls) might not be represented accurately.<br>
 * * The vertical unit for measurement of elevation height is meters. An elevation value of -32767.0 is used for points that have no data value, most often returned where there isn't landmass (i.e. water).<br>
 * * The horizontal reference datum is the World Geodetic System 1984 (WGS84-G1150) and the vertical reference datum is the Earth Gravitational Model 2008 (EGM2008).<br>
 * * Tiles are 258x258 pixel squares rather than the standard 256 x 256. This is done to allow for accurate interpolation of values at the tile edges. As such adjacent tiles overlap by 1 pixel along all edges.<br>
 * * Tile data comes from the [Airbus WorldDEM4Ortho product](https:\/\/www.intelligence-airbusds.com\/worlddem-streaming\/). Urban areas are approximately leveled down to ground level. All other areas are represented by the object surface level (e.g., trees). <br>
 *
 * Supports zoom level 13 only. Format: raster (tiff).
 */
export type TilesetID = string;

/** Known values of {@link TileSize} that the service accepts. */
export const enum KnownTileSize {
  /**
   * Return a 256 by 256 pixel tile. Available for all tilesetIds except for
   * * microsoft.terra.main
   */
  TwoHundredFiftySix = "256",
  /**
   * Return a 512 by 512 pixel tile.  Available for all tilesetIds except for
   * * microsoft.weather.radar.main
   * * microsoft.weather.infrared.main
   * * microsoft.base.hybrid
   * * microsoft.dem
   * * microsoft.imagery
   */
  FiveHundredTwelve = "512"
}

/**
 * Defines values for TileSize. \
 * {@link KnownTileSize} can be used interchangeably with TileSize,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **256**: Return a 256 by 256 pixel tile. Available for all tilesetIds except for
 * * microsoft.terra.main \
 * **512**: Return a 512 by 512 pixel tile.  Available for all tilesetIds except for
 * * microsoft.weather.radar.main
 * * microsoft.weather.infrared.main
 * * microsoft.base.hybrid
 * * microsoft.dem
 * * microsoft.imagery
 */
export type TileSize = string;

/** Known values of {@link GeographicResourceLocation} that the service accepts. */
export const enum KnownGeographicResourceLocation {
  /** Used to access an Azure Maps Creator resource in the United States */
  Us = "us",
  /** Used to access an Azure Maps Creator resource in Europe */
  Eu = "eu"
}

/**
 * Defines values for GeographicResourceLocation. \
 * {@link KnownGeographicResourceLocation} can be used interchangeably with GeographicResourceLocation,
 *  this enum contains the known values that the service supports.
 * ### Known values supported by the service
 * **us**: Used to access an Azure Maps Creator resource in the United States \
 * **eu**: Used to access an Azure Maps Creator resource in Europe
 */
export type GeographicResourceLocation = string;

/** Optional parameters. */
export interface RenderGetMapStaticImageOptionalParams
  extends coreClient.OperationOptions {
  /** Map layer requested. If layer is set to labels or hybrid, the format should be png. */
  layer?: StaticMapLayer;
  /** Map style to be returned. Possible values are main and dark. */
  style?: MapImageStyle;
  /** Desired zoom level of the map. Zoom value must be in the range: 0-20 (inclusive). Default value is 12.<br><br>Please see [Zoom Levels and Tile Grid](https://docs.microsoft.com/en-us/azure/location-based-services/zoom-levels-and-tile-grid) for details. */
  zoom?: number;
  /**
   * Coordinates of the center point. Format: 'lon,lat'. Projection used
   * - EPSG:3857. Longitude range: -180 to 180. Latitude range: -85 to 85.
   *
   * Note: Either center or bbox are required parameters. They are
   * mutually exclusive.
   */
  center?: string;
  /**
   * Bounding box. Projection used - EPSG:3857. Format : 'minLon, minLat,
   * maxLon, maxLat'.
   *
   * Note: Either bbox or center are required
   * parameters. They are mutually exclusive. It shouldn’t be used with
   * height or width.
   *
   * The maximum allowed ranges for Lat and Lon are defined for each zoom level
   * in the table at the top of this page.
   */
  bbox?: string;
  /**
   * Height of the resulting image in pixels. Range is 1 to 8192. Default
   * is 512. It shouldn’t be used with bbox.
   */
  height?: number;
  /** Width of the resulting image in pixels. Range is 1 to 8192. Default is 512. It shouldn’t be used with bbox. */
  width?: number;
  /**
   * Language in which search results should be returned. Should be one of supported IETF language tags, case insensitive. When data in specified language is not available for a specific field, default language is used.
   *
   * Please refer to [Supported Languages](https://docs.microsoft.com/en-us/azure/azure-maps/supported-languages) for details.
   */
  language?: string;
  /**
   * The View parameter specifies which set of geopolitically disputed content is returned via Azure Maps services, including  borders and labels displayed on the map. The View parameter (also referred to as “user region parameter”) will show the  correct maps for that country/region. By default, the View parameter is set to “Unified” even if you haven’t defined it in  the request. It is your responsibility to determine the location of your users, and then set the View parameter correctly  for that location. Alternatively, you have the option to set ‘View=Auto’, which will return the map data based on the IP  address of the request. The View parameter in Azure Maps must be used in compliance with applicable laws, including those  regarding mapping, of the country where maps, images and other data and third party content that you are authorized to  access via Azure Maps is made available. Example: view=IN.
   *
   * Please refer to [Supported Views](https://aka.ms/AzureMapsLocalizationViews) for details and to see the available Views.
   */
  view?: string;
  /**
   * Pushpin style and instances. Use this parameter to optionally add pushpins to the image.
   * The pushpin style describes the appearance of the pushpins, and the instances specify
   * the coordinates of the pushpins and optional labels for each pin. (Be sure to properly URL-encode values of this
   * parameter since it will contain reserved characters such as pipes and punctuation.)
   *
   * The Azure Maps account S0 SKU only supports a single instance of the pins parameter. Other SKUs
   * allow multiple instances of the pins parameter to specify multiple pin styles.
   *
   * To render a pushpin at latitude 45°N and longitude 122°W using the default built-in pushpin style, add the
   * querystring parameter
   *
   * `pins=default||-122 45`
   *
   * Note that the longitude comes before the latitude.
   * After URL encoding this will look like
   *
   * `pins=default%7C%7C-122+45`
   *
   * All of the examples here show the pins
   * parameter without URL encoding, for clarity.
   *
   * To render a pin at multiple locations, separate each location with a pipe character. For example, use
   *
   * `pins=default||-122 45|-119.5 43.2|-121.67 47.12`
   *
   * The S0 Azure Maps account SKU only allows five pushpins. Other account SKUs do not have this limitation.
   *
   * ### Style Modifiers
   *
   * You can modify the appearance of the pins by adding style modifiers. These are added after the style but before
   * the locations and labels. Style modifiers each have a two-letter name. These abbreviated names are used to help
   * reduce the length of the URL.
   *
   * To change the color of the pushpin, use the 'co' style modifier and specify the color using the HTML/CSS RGB color
   * format which is a six-digit hexadecimal number (the three-digit form is not supported). For example, to use
   * a deep pink color which you would specify as #FF1493 in CSS, use
   *
   * `pins=default|coFF1493||-122 45`
   *
   * ### Pushpin Labels
   *
   * To add a label to the pins, put the label in single quotes just before the coordinates. For example, to label
   * three pins with the values '1', '2', and '3', use
   *
   * `pins=default||'1'-122 45|'2'-119.5 43.2|'3'-121.67 47.12`
   *
   * There is a built in pushpin style called 'none' that does not display a pushpin image. You can use this if
   * you want to display labels without any pin image. For example,
   *
   * `pins=none||'A'-122 45|'B'-119.5 43.2`
   *
   * To change the color of the pushpin labels, use the 'lc' label color style modifier. For example, to use pink
   * pushpins with black labels, use
   *
   * `pins=default|coFF1493|lc000000||-122 45`
   *
   * To change the size of the labels, use the 'ls' label size style modifier. The label size represents the approximate
   * height of the label text in pixels. For example, to increase the label size to 12, use
   *
   * `pins=default|ls12||'A'-122 45|'B'-119 43`
   *
   * The labels are centered at the pushpin 'label anchor.' The anchor location is predefined for built-in pushpins and
   * is at the top center of custom pushpins (see below). To override the label anchor, using the 'la' style modifier
   * and provide X and Y pixel coordinates for the anchor. These coordinates are relative to the top left corner of the
   * pushpin image. Positive X values move the anchor to the right, and positive Y values move the anchor down. For example,
   * to position the label anchor 10 pixels right and 4 pixels above the top left corner of the pushpin image,
   * use
   *
   * `pins=default|la10 -4||'A'-122 45|'B'-119 43`
   *
   * ### Custom Pushpins
   *
   * To use a custom pushpin image, use the word 'custom' as the pin style name, and then specify a URL after the
   * location and label information. Use two pipe characters to indicate that you're done specifying locations and are
   * starting the URL. For example,
   *
   * `pins=custom||-122 45||http://contoso.com/pushpins/red.png`
   *
   * After URL encoding, this would look like
   *
   * `pins=custom%7C%7C-122+45%7C%7Chttp%3A%2F%2Fcontoso.com%2Fpushpins%2Fred.png`
   *
   * By default, custom pushpin images are drawn centered at the pin coordinates. This usually isn't ideal as it obscures
   * the location that you're trying to highlight. To override the anchor location of the pin image, use the 'an'
   * style modifier. This uses the same format as the 'la' label anchor style modifier. For example, if your custom
   * pin image has the tip of the pin at the top left corner of the image, you can set the anchor to that spot by
   * using
   *
   * `pins=custom|an0 0||-122 45||http://contoso.com/pushpins/red.png`
   *
   * Note: If you use the 'co' color modifier with a custom pushpin image, the specified color will replace the RGB
   * channels of the pixels in the image but will leave the alpha (opacity) channel unchanged. This would usually
   * only be done with a solid-color custom image.
   *
   * ### Getting Pushpins from Azure Maps Data Storage
   *
   * For all Azure Maps account SKUs other than S0,
   * the pushpin image and location information can be obtained from Azure Maps Data Storage. After uploading a pushpin image
   * or a GeoJSON document containing pin locations, the Data Storage service returns a Unique Data ID (UDID) that you can use
   * to reference the data in the pins parameter.
   *
   * To use a custom pushpin image from Azure Maps Data Storage, specify the UDID prefixed by 'udid-' as the name of the
   * pushpin style. For example,
   *
   * `pins=udid-fe22c504-3a81-4fcd-adc6-a3507ce866c1||-122 45`
   *
   * To use the point geometry from an uploaded GeoJSON document as the pin locations, specify the UDID in the locations
   * section of the pins parameter. For example,
   *
   * `pins=default||udid-29dc105a-dee7-409f-a3f9-22b066ae4713`
   *
   * Note that
   * only point and multipoint geometry, points and multipoints from geometry collections, and point geometry from features
   * will be used. Linestring and polygon geometry will be ignored. If the point comes from a feature and the feature
   * has a string property called "label", the value of that property will be used as the label for the pin.
   *
   * You can mix pin locations from Data Storage and pin locations specified in the pins parameter. Any of the pipe-delimited
   * pin locations can be a longitude and latitude or a UDID. For example,
   *
   * `pins=default||-122 45|udid-29dc105a-dee7-409f-a3f9-22b066ae4713|-119 43`
   *
   * ### Scale, Rotation, and Opacity
   *
   * You can make pushpins and their labels larger or smaller by using the 'sc' scale style modifier. This is a
   * value greater than zero. A value of 1 is the standard scale. Values larger than 1 will make the pins larger, and
   * values smaller than 1 will make them smaller. For example, to draw the pushpins 50% larger than normal, use
   *
   * `pins=default|sc1.5||-122 45`
   *
   * You can rotate pushpins and their labels by using the 'ro' rotation style modifier. This is a number of degrees
   * of clockwise rotation. Use a negative number to rotate counter-clockwise. For example, to rotate the pushpins
   * 90 degrees clockwise and double their size, use
   *
   * `pins=default|ro90|sc2||-122 45`
   *
   * You can make pushpins and their labels partially transparent by specifying the 'al' alpha style modifier.
   * This is a number between 0 and 1 indicating the opacity of the pushpins. Zero makes them completely transparent
   * (and not visible) and 1 makes them completely opaque (which is the default). For example, to make pushpins
   * and their labels only 67% opaque, use
   *
   * `pins=default|al.67||-122 45`
   *
   * ### Style Modifier Summary
   *
   * Modifier  | Description     | Range
   * :--------:|-----------------|------------------
   * al        | Alpha (opacity) | 0 to 1
   * an        | Pin anchor      | *
   * co        | Pin color       | 000000 to FFFFFF
   * la        | Label anchor    | *
   * lc        | Label color     | 000000 to FFFFFF
   * ls        | Label size      | Greater than 0
   * ro        | Rotation        | -360 to 360
   * sc        | Scale           | Greater than 0
   *
   * * X and Y coordinates can be anywhere within pin image or a margin around it.
   * The margin size is the minimum of the pin width and height.
   */
  pins?: string[];
  /**
   * Path style and locations. Use this parameter to optionally add lines, polygons or circles to the image.
   * The path style describes the appearance of the line and fill. (Be sure to properly URL-encode values of this
   * parameter since it will contain reserved characters such as pipes and punctuation.)
   *
   * Path parameter is supported in Azure Maps account SKU starting with S1. Multiple instances of the path parameter
   * allow to specify multiple geometries with their styles. Number of parameters per request is limited to 10 and
   * number of locations is limited to 100 per path.
   *
   * To render a circle with radius 100 meters and center point at latitude 45°N and longitude 122°W using the default style, add the
   * querystring parameter
   *
   * `path=ra100||-122 45`
   *
   * Note that the longitude comes before the latitude.
   * After URL encoding this will look like
   *
   * `path=ra100%7C%7C-122+45`
   *
   * All of the examples here show the path parameter without URL encoding, for clarity.
   *
   * To render a line, separate each location with a pipe character. For example, use
   *
   * `path=||-122 45|-119.5 43.2|-121.67 47.12`
   *
   * To render a polygon, last location must be equal to the start location. For example, use
   *
   * `path=||-122 45|-119.5 43.2|-121.67 47.12|-122 45`
   *
   * Longitude and latitude values for locations of lines and polygons can be in the range from -360 to 360 to allow for rendering of geometries crossing the anti-meridian.
   *
   * ### Style Modifiers
   *
   * You can modify the appearance of the path by adding style modifiers. These are added before the locations.
   * Style modifiers each have a two-letter name. These abbreviated names are used to help reduce the length
   * of the URL.
   *
   * To change the color of the outline, use the 'lc' style modifier and specify the color using the HTML/CSS RGB color
   * format which is a six-digit hexadecimal number (the three-digit form is not supported). For example, to use
   * a deep pink color which you would specify as #FF1493 in CSS, use
   *
   * `path=lcFF1493||-122 45|-119.5 43.2`
   *
   * Multiple style modifiers may be combined together to create a more complex visual style.
   *
   * `lc0000FF|lw3|la0.60|fa0.50||-122.2 47.6|-122.2 47.7|-122.3 47.7|-122.3 47.6|-122.2 47.6`
   *
   * ### Getting Path locations from Azure Maps Data Storage
   *
   * For all Azure Maps account SKUs other than S0, the path location information can be obtained from Azure Maps Data Storage.
   * After uploading a GeoJSON document containing path locations, the Data Storage service returns a Unique Data ID (UDID) that you can use
   * to reference the data in the path parameter.
   *
   * To use the point geometry from an uploaded GeoJSON document as the path locations, specify the UDID in the locations
   * section of the path parameter. For example,
   *
   * `path=||udid-29dc105a-dee7-409f-a3f9-22b066ae4713`
   *
   * Note the it is not allowed to mix path locations from Data Storage with locations specified in the path parameter.
   *
   * ### Style Modifier Summary
   *
   * Modifier  | Description            | Range
   * :--------:|------------------------|------------------
   * lc        | Line color             | 000000 to FFFFFF
   * fc        | Fill color             | 000000 to FFFFFF
   * la        | Line alpha (opacity)   | 0 to 1
   * fa        | Fill alpha (opacity)   | 0 to 1
   * lw        | Line width             | Greater than 0
   * ra        | Circle radius (meters) | Greater than 0
   */
  path?: string[];
}

/** Contains response data for the getMapStaticImage operation. */
export type RenderGetMapStaticImageResponse = RenderGetMapStaticImageHeaders & {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always `undefined` in node.js.
   */
  blobBody?: Promise<Blob>;
  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always `undefined` in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;
};

/** Optional parameters. */
export interface RenderGetMapTileOptionalParams
  extends coreClient.OperationOptions {
  /**
   * Language in which search results should be returned. Should be one of supported IETF language tags, case insensitive. When data in specified language is not available for a specific field, default language is used.
   *
   * Please refer to [Supported Languages](https://docs.microsoft.com/en-us/azure/azure-maps/supported-languages) for details.
   */
  language?: string;
  /**
   * The View parameter specifies which set of geopolitically disputed content is returned via Azure Maps services, including  borders and labels displayed on the map. The View parameter (also referred to as “user region parameter”) will show the  correct maps for that country/region. By default, the View parameter is set to “Unified” even if you haven’t defined it in  the request. It is your responsibility to determine the location of your users, and then set the View parameter correctly  for that location. Alternatively, you have the option to set ‘View=Auto’, which will return the map data based on the IP  address of the request. The View parameter in Azure Maps must be used in compliance with applicable laws, including those  regarding mapping, of the country where maps, images and other data and third party content that you are authorized to  access via Azure Maps is made available. Example: view=IN.
   *
   * Please refer to [Supported Views](https://aka.ms/AzureMapsLocalizationViews) for details and to see the available Views.
   */
  view?: string;
  /** The size of the returned map tile in pixels. */
  tileSize?: MapTileSize;
}

/** Contains response data for the getMapTile operation. */
export type RenderGetMapTileResponse = RenderGetMapTileHeaders & {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always `undefined` in node.js.
   */
  blobBody?: Promise<Blob>;
  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always `undefined` in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;
};

/** Optional parameters. */
export interface RenderGetMapStateTilePreviewOptionalParams
  extends coreClient.OperationOptions {}

/** Contains response data for the getMapStateTilePreview operation. */
export type RenderGetMapStateTilePreviewResponse = RenderGetMapStateTilePreviewHeaders & {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always `undefined` in node.js.
   */
  blobBody?: Promise<Blob>;
  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always `undefined` in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;
};

/** Optional parameters. */
export interface RenderGetCopyrightCaptionOptionalParams
  extends coreClient.OperationOptions {}

/** Contains response data for the getCopyrightCaption operation. */
export type RenderGetCopyrightCaptionResponse = GetCopyrightCaptionResult;

/** Optional parameters. */
export interface RenderGetMapImageryTileOptionalParams
  extends coreClient.OperationOptions {}

/** Contains response data for the getMapImageryTile operation. */
export type RenderGetMapImageryTileResponse = RenderGetMapImageryTileHeaders & {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always `undefined` in node.js.
   */
  blobBody?: Promise<Blob>;
  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always `undefined` in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;
};

/** Optional parameters. */
export interface RenderGetCopyrightFromBoundingBoxOptionalParams
  extends coreClient.OperationOptions {
  /** Yes/no value to exclude textual data from response. Only images and country names will be in response. */
  text?: IncludeText;
}

/** Contains response data for the getCopyrightFromBoundingBox operation. */
export type RenderGetCopyrightFromBoundingBoxResponse = GetCopyrightFromBoundingBoxResult;

/** Optional parameters. */
export interface RenderGetCopyrightForTileOptionalParams
  extends coreClient.OperationOptions {
  /** Yes/no value to exclude textual data from response. Only images and country names will be in response. */
  text?: IncludeText;
}

/** Contains response data for the getCopyrightForTile operation. */
export type RenderGetCopyrightForTileResponse = GetCopyrightForTileResult;

/** Optional parameters. */
export interface RenderGetCopyrightForWorldOptionalParams
  extends coreClient.OperationOptions {
  /** Yes/no value to exclude textual data from response. Only images and country names will be in response. */
  text?: IncludeText;
}

/** Contains response data for the getCopyrightForWorld operation. */
export type RenderGetCopyrightForWorldResponse = GetCopyrightForWorldResult;

/** Optional parameters. */
export interface RenderV2GetMapTilePreviewOptionalParams
  extends coreClient.OperationOptions {
  /**
   * Language in which search results should be returned. Should be one of supported IETF language tags, case insensitive. When data in specified language is not available for a specific field, default language is used.
   *
   * Please refer to [Supported Languages](https://docs.microsoft.com/en-us/azure/azure-maps/supported-languages) for details.
   */
  language?: string;
  /**
   * The View parameter specifies which set of geopolitically disputed content is returned via Azure Maps services, including  borders and labels displayed on the map. The View parameter (also referred to as “user region parameter”) will show the  correct maps for that country/region. By default, the View parameter is set to “Unified” even if you haven’t defined it in  the request. It is your responsibility to determine the location of your users, and then set the View parameter correctly  for that location. Alternatively, you have the option to set ‘View=Auto’, which will return the map data based on the IP  address of the request. The View parameter in Azure Maps must be used in compliance with applicable laws, including those  regarding mapping, of the country where maps, images and other data and third party content that you are authorized to  access via Azure Maps is made available. Example: view=IN.
   *
   * Please refer to [Supported Views](https://aka.ms/AzureMapsLocalizationViews) for details and to see the available Views.
   */
  view?: string;
  /**
   * The desired date and time of the requested tile. This parameter must be specified in the standard date-time format (e.g. 2019-11-14T16:03:00-08:00), as defined by [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601). This parameter is only supported when tilesetId parameter is set to one of the values below.
   *
   * * microsoft.weather.infrared.main: We provide tiles up to 3 hours in the past. Tiles are available in 10-minute intervals. We round the timeStamp value to the nearest 10-minute time frame.
   * * microsoft.weather.radar.main: We provide tiles up to 1.5 hours in the past and up to 2 hours in the future. Tiles are available in 5-minute intervals. We round the timeStamp value to the nearest 5-minute time frame.
   */
  timeStamp?: string;
  /** The size of the returned map tile in pixels. */
  tileSize?: TileSize;
}

/** Contains response data for the getMapTilePreview operation. */
export type RenderV2GetMapTilePreviewResponse = RenderV2GetMapTilePreviewHeaders & {
  /**
   * BROWSER ONLY
   *
   * The response body as a browser Blob.
   * Always `undefined` in node.js.
   */
  blobBody?: Promise<Blob>;
  /**
   * NODEJS ONLY
   *
   * The response body as a node.js Readable stream.
   * Always `undefined` in the browser.
   */
  readableStreamBody?: NodeJS.ReadableStream;
};

/** Optional parameters. */
export interface RenderClientOptionalParams
  extends coreClient.ServiceClientOptions {
  /** This parameter specifies where the Azure Maps Creator resource is located.  Valid values are us and eu. */
  geography?: Geography;
  /** Specifies which account is intended for usage in conjunction with the Azure AD security model.  It represents a unique ID for the Azure Maps account and can be retrieved from the Azure Maps management  plane Account API. To use Azure AD security in Azure Maps see the following [articles](https://aka.ms/amauthdetails) for guidance. */
  xMsClientId?: string;
  /** Overrides client endpoint. */
  endpoint?: string;
}
